version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies with legacy-peer-deps..."
      - npm install --legacy-peer-deps
  preBuild:
    commands:
      - echo "Pre-building steps..."
  build:
    commands:
      - echo "Building the frontend..."
      - npm run build  # Your custom build command
  postBuild:
    commands:
      - echo "Build completed!"

artifacts:
  baseDirectory: build  # The directory where the build output is located
  files:
    - '**/*'  # Include all files inside the build directory

cache:
  paths:
    - node_modules/**/*

frontend:
  framework: "React"  # Explicitly mention React as the frontend framework
