// matchupsActionTypes.js
export const FETCH_UPCOMING_ODDS_REQUEST = 'FETCH_UPCOMING_ODDS_REQUEST';
export const FETCH_UPCOMING_ODDS_SUCCESS = 'FETCH_UPCOMING_ODDS_SUCCESS';
export const FETCH_UPCOMING_ODDS_FAILURE = 'FETCH_UPCOMING_ODDS_FAILURE';
export const FETCH_PAST_ODDS_REQUEST = 'FETCH_PAST_ODDS_REQUEST';
export const FETCH_PAST_ODDS_SUCCESS = 'FETCH_PAST_ODDS_SUCCESS';
export const FETCH_PAST_ODDS_FAILURE = 'FETCH_PAST_ODDS_FAILURE';
export const SET_ODDS = 'SET_ODDS'
export const SET_PAST_ODDS = 'SET_PAST_ODDS'