export const sports = [
  {
    name: "americanfootball_nfl", espnSport: 'football', league: 'NFL', startMonth: 9, endMonth: 2, multiYear: true, statYear: 2024, decayFactor: 0.95, valueBetSettings: {
      winPercentIncrease: 0,
      indexDiffSmallNum: 0,
      indexDiffRangeNum: 0,
      confidenceLowNum: 0,
      confidenceRangeNum: 0
    }
  },
  {
    name: "basketball_nba", espnSport: 'basketball', league: 'NBA', startMonth: 10, endMonth: 4, multiYear: true, statYear: 2025, decayFactor: 0.85, valueBetSettings: {
      winPercentIncrease: 30,
      indexDiffSmallNum: 40,
      indexDiffRangeNum: 25,
      confidenceLowNum: .9,
      confidenceRangeNum: .35
    }
  },
  {
    name: "icehockey_nhl", espnSport: 'hockey', league: 'NHL', startMonth: 10, endMonth: 4, multiYear: true, statYear: 2025, prevstatYear: 2024, decayFactor: 0.85, valueBetSettings: {
      winPercentIncrease: 15,
      indexDiffSmallNum: 30,
      indexDiffRangeNum: 35,
      confidenceLowNum: .55,
      confidenceRangeNum: .2
    }
  },
  {
    name: "baseball_mlb", espnSport: 'baseball', league: 'MLB', startMonth: 3, endMonth: 10, multiYear: false, statYear: 2024, decayFactor: 0.75, valueBetSettings: {
      winPercentIncrease: 0,
      indexDiffSmallNum: 0,
      indexDiffRangeNum: 0,
      confidenceLowNum: 0,
      confidenceRangeNum: 0
    }
  },
  {
    name: "americanfootball_ncaaf", espnSport: 'football', league: 'NCAAF', startMonth: 9, endMonth: 1, multiYear: true, statYear: 2024, decayFactor: 0.90, valueBetSettings: {
      winPercentIncrease: 0,
      indexDiffSmallNum: 0,
      indexDiffRangeNum: 0,
      confidenceLowNum: 0,
      confidenceRangeNum: 0
    }
  },
  {
    name: "basketball_ncaab", espnSport: 'basketball', league: 'NCAAB', startMonth: 11, endMonth: 4, multiYear: true, statYear: 2025, decayFactor: 0.85, valueBetSettings: {
      winPercentIncrease: 10,
      indexDiffSmallNum: 25,
      indexDiffRangeNum: 30,
      confidenceLowNum: .8,
      confidenceRangeNum: .1
    }
  },
  {
    name: "basketball_wncaab", espnSport: 'basketball', league: 'WNCAAB', startMonth: 11, endMonth: 4, multiYear: true, statYear: 2025, decayFactor: 0.85, valueBetSettings: {
      winPercentIncrease: 50,
      indexDiffSmallNum: 45,
      indexDiffRangeNum: 30,
      confidenceLowNum: .8,
      confidenceRangeNum: .5
    }
  },
]

export const generalStats = {
  'seasonWinLoss': 'Season Win-Loss Record',
  'homeWinLoss': 'Home Win-Loss Record',
  'awayWinLoss': 'Away Win-Loss Record',
  'pointDiff': 'Point Differential',
  'BSKBtotalPoints': 'Total Points',
  'BSKBpointsPerGame': 'Points per Game',
  'BSKBassists': 'Assists',
  'BSKBassistsPerGame': 'Assists per Game',
  'HKYgoals': 'Goals',
  'HKYgoalsPerGame': 'Goals per Game',
  'HKYassists': 'Assists',
  'HKYassistsPerGame': 'Assists per Game',
  'HKYfaceoffs': 'Faceoffs',
  'HKYfaceoffsPerGame': 'Faceoffs per Game',
  'HKYfaceoffsWon': 'Faceoffs Won',
  'HKYfaceoffsWonPerGame': 'Faceoffs Won per Game',
  'HKYfaceoffsLost': 'Faceoffs Lost',
  'HKYfaceoffsLostPerGame': 'Faceoffs Lost per Game',
  'HKYfaceoffPct': 'Faceoff Percentage',
  'HKYfaceoffPctPerGame': 'Faceoff Percentage per Game',
  'USFBtotalFirstDowns': 'Total First Downs',
  'USFBthirdDownEfficiency': 'Third Down Efficiency',
  'USFBpassingYards': 'Passing Yards',
  'USFBreceivingYards': 'Receiving Yards',
  'USFBrushingYards': 'Rushing Yards',
  'USFBsacksPerGame': 'Sacks per Game',
  'USFBfieldGoalsMade': 'Field Goals Made',
  'USFBtotalTouchdowns': 'Total Touchdowns',
  'USFBtouchdownsPerGame': 'Touchdowns per Game',
  'USFBtotalPoints': 'Total Points',
  'USFBpointsPerGame': 'Points per Game',
  'USFBtotalPenyards': 'Total Penalty Yards',
  'USFBaveragePenYardsPerGame': 'Average Penalty Yards per Game',
  'USFBgiveaways': 'Giveaways',
  'USFBtakeaways': 'Takeaways',
  'USFBturnoverDiff': 'Turnover Differential',

}
export const offenseStats = {
  'BSKBtotalPoints': 'Total Points',
  'BSKBpointsPerGame': 'Points per Game',
  'BSKBassists': 'Assists',
  'BSKBassistsPerGame': 'Assists per Game',
  'BSKBassistRatio': 'Assist Ratio',
  'BSKBeffectiveFgPercent': 'Effective Field Goal Percentage',
  'BSKBfieldGoalPercent': 'Field Goal Percentage',
  'BSKBfieldGoalsAttempted': 'Field Goals Attempted',
  'BSKBfieldGoalsMade': 'Field Goals Made',
  'BSKBfieldGoalsPerGame': 'Field Goals per Game',
  'BSKBfreeThrowPercent': 'Free Throw Percentage',
  'BSKBfreeThrowsAttempted': 'Free Throws Attempted',
  'BSKBfreeThrowsMade': 'Free Throws Made',
  'BSKBfreeThrowsMadePerGame': 'Free Throws Made per Game',
  'BSKBoffensiveRebounds': 'Offensive Rebounds',
  'BSKBoffensiveReboundsPerGame': 'Offensive Rebounds per Game',
  'BSKBoffensiveReboundRate': 'Offensive Rebound Rate',
  'BSKBoffensiveTurnovers': 'Offensive Turnovers',
  'BSKBturnoversPerGame': 'Turnovers per Game',
  'BSKBturnoverRatio': 'Turnover Ratio',
  'BSKBthreePointPct': 'Three-Point Percentage',
  'BSKBthreePointsAttempted': 'Three-Point Attempts',
  'BSKBthreePointsMade': 'Three-Point Made',
  'BSKBtrueShootingPct': 'True Shooting Percentage',
  'BSKBpace': 'Pace',
  'BSKBpointsInPaint': 'Points in the Paint',
  'BSKBshootingEfficiency': 'Shooting Efficiency',
  'BSKBscoringEfficiency': 'Scoring Efficiency',
  'HKYgoals': 'Goals',
  'HKYgoalsPerGame': 'Goals per Game',
  'HKYassists': 'Assists',
  'HKYassistsPerGame': 'Assists per Game',
  'HKYshotsIn1st': 'Shots in 1st Period',
  'HKYshotsIn1stPerGame': 'Shots in 1st Period per Game',
  'HKYshotsIn2nd': 'Shots in 2nd Period',
  'HKYshotsIn2ndPerGame': 'Shots in 2nd Period per Game',
  'HKYshotsIn3rd': 'Shots in 3rd Period',
  'HKYshotsIn3rdPerGame': 'Shots in 3rd Period per Game',
  'HKYtotalShots': 'Total Shots',
  'HKYtotalShotsPerGame': 'Total Shots per Game',
  'HKYshotsMissed': 'Shots Missed',
  'HKYshotsMissedPerGame': 'Shots Missed per Game',
  'HKYppgGoals': 'Power Play Goals',
  'HKYppgGoalsPerGame': 'Power Play Goals per Game',
  'HKYppassists': 'Power Play Assists',
  'HKYppassistsPerGame': 'Power Play Assists per Game',
  'HKYpowerplayPct': 'Power Play Percentage',
  'HKYshortHandedGoals': 'Shorthanded Goals',
  'HKYshortHandedGoalsPerGame': 'Shorthanded Goals per Game',
  'HKYshootingPct': 'Shooting Percentage',
  'HKYfaceoffs': 'Faceoffs',
  'HKYfaceoffsPerGame': 'Faceoffs per Game',
  'HKYfaceoffsWon': 'Faceoffs Won',
  'HKYfaceoffsWonPerGame': 'Faceoffs Won per Game',
  'HKYfaceoffsLost': 'Faceoffs Lost',
  'HKYfaceoffsLostPerGame': 'Faceoffs Lost per Game',
  'HKYfaceoffPct': 'Faceoff Percentage',
  'HKYfaceoffPctPerGame': 'Faceoff Percentage per Game',
  'HKYgiveaways': 'Giveaways',
  'HKYshotDifferential': 'Shot Differential',
  'HKYshotDifferentialPerGame': 'Shot Differential per Game',
  'HKYgoalDifferentialPerGame': 'Goal Differential per Game',
}
export const defenseStats = {
  'BSKBblocks': 'Blocks',
  'BSKBblocksPerGame': 'Blocks per Game',
  'BSKBdefensiveRebounds': 'Defensive Rebounds',
  'BSKBdefensiveReboundsPerGame': 'Defensive Rebounds per Game',
  'BSKBsteals': 'Steals',
  'BSKBstealsPerGame': 'Steals per Game',
  'BSKBreboundRate': 'Rebound Rate',
  'BSKBreboundsPerGame': 'Rebounds per Game',
  'BSKBfoulsPerGame': 'Fouls per Game',
  'BSKBteamAssistToTurnoverRatio': 'Team Assist to Turnover Ratio',
  'HKYgoalsAgainst': 'Goals Against',
  'HKYgoalsAgainstPerGame': 'Goals Against per Game',
  'HKYshotsAgainst': 'Shots Against',
  'HKYshotsAgainstPerGame': 'Shots Against per Game',
  'HKYpenaltyKillPct': 'Penalty Kill Percentage',
  'HKYpenaltyKillPctPerGame': 'Penalty Kill Percentage per Game',
  'HKYppGoalsAgainst': 'Power Play Goals Against',
  'HKYppGoalsAgainstPerGame': 'Power Play Goals Against per Game',
  'HKYshutouts': 'Shutouts',
  'HKYsaves': 'Saves',
  'HKYsavesPerGame': 'Saves per Game',
  'HKYsavePct': 'Save Percentage',
  'HKYblockedShots': 'Blocked Shots',
  'HKYblockedShotsPerGame': 'Blocked Shots per Game',
  'HKYhits': 'Hits',
  'HKYhitsPerGame': 'Hits per Game',
  'HKYtakeaways': 'Takeaways',
  'HKYtakeawaysPerGame': 'Takeaways per Game',
  'USFBtacklesforLoss': 'Tackles for Loss',
  'USFBtacklesforLossPerGame': 'Tackles for Loss per Game',
  'USFBinterceptions': 'Interceptions',
  'USFByardsPerInterception': 'Yards per Interception',
  'USFBsacksTotal': 'Total Sacks',
  'USFBsacksPerGame': 'Sacks per Game',
  'USFBsackYards': 'Sack Yards',
  'USFBsackYardsPerGame': 'Sack Yards per Game',
  'USFBstuffs': 'Stuffs',
  'USFBstuffsPerGame': 'Stuffs per Game',
  'USFBstuffYards': 'Stuff Yards',
  'USFBpassesDefended': 'Passes Defended',
  'USFBpassesDefendedPerGame': 'Passes Defended per Game',
  'USFBsafties': 'Safeties',
}
export const passingStats = {
  'USFBcompletionPercent': 'Completion Percentage',
  'USFBcompletions': 'Completions',
  'USFBcompletionsPerGame': 'Completions per Game',
  'USFBnetPassingYards': 'Net Passing Yards',
  'USFBnetPassingYardsPerGame': 'Net Passing Yards per Game',
  'USFBpassingFirstDowns': 'Passing First Downs',
  'USFBpassingTouchdowns': 'Passing Touchdowns',
  'USFBpassingYards': 'Passing Yards',
  'USFBpassingYardsPerGame': 'Passing Yards per Game',
  'USFBpassingAttempts': 'Passing Attempts',
  'USFBpassingAttemptsPerGame': 'Passing Attempts per Game',
  'USFByardsPerPassAttempt': 'Yards per Pass Attempt',
}
export const receivingStats = {
  'USFBreceivingFirstDowns': 'Receiving First Downs',
  'USFBreceivingTouchdowns': 'Receiving Touchdowns',
  'USFBreceivingYards': 'Receiving Yards',
  'USFBreceivingYardsPerGame': 'Receiving Yards per Game',
  'USFBreceivingYardsPerReception': 'Receiving Yards per Reception',
  'USFBreceivingYardsAfterCatch': 'Receiving Yards After Catch',
  'USFBreceivingYardsAfterCatchPerGame': 'Receiving Yards After Catch per Game',
}
export const rushingStats = {
  'USFBrushingAttempts': 'Rushing Attempts',
  'USFBrushingFirstDowns': 'Rushing First Downs',
  'USFBrushingTouchdowns': 'Rushing Touchdowns',
  'USFBrushingYards': 'Rushing Yards',
  'USFBrushingYardsPerGame': 'Rushing Yards per Game',
  'USFByardsPerRushAttempt': 'Yards per Rush Attempt',
}
export const kickingStats = {
  'USFBaverageKickoffYards': 'Average Kickoff Yards',
  'USFBaverageKickoffYardsPerGame': 'Average Kickoff Yards per Game',
  'USFBextraPointAttempts': 'Extra Point Attempts',
  'USFBextraPointAttemptsPerGame': 'Extra Point Attempts per Game',
  'USFBextraPointsMade': 'Extra Points Made',
  'USFBextraPointsMadePerGame': 'Extra Points Made per Game',
  'USFBextraPointPercent': 'Extra Point Percentage',
  'USFBextraPointPercentPerGame': 'Extra Point Percentage per Game',
  'USFBfieldGoalAttempts': 'Field Goal Attempts',
  'USFBfieldGoalAttemptsPerGame': 'Field Goal Attempts per Game',
  'USFBfieldGoalsMade': 'Field Goals Made',
  'USFBfieldGoalsMadePerGame': 'Field Goals Made per Game',
  'USFBfieldGoalPct': 'Field Goal Percentage',
  'USFBfieldGoalPercentPerGame': 'Field Goal Percentage per Game',
  'USFBtouchbacks': 'Touchbacks',
  'USFBtouchbacksPerGame': 'Touchbacks per Game',
  'USFBtouchBackPercentage': 'Touchback Percentage',
}
export const returningStats = {
  'USFBkickReturns': 'Kick Returns',
  'USFBkickReturnsPerGame': 'Kick Returns per Game',
  'USFBkickReturnYards': 'Kick Return Yards',
  'USFBkickReturnYardsPerGame': 'Kick Return Yards per Game',
  'USFBpuntReturns': 'Punt Returns',
  'USFBpuntReturnsPerGame': 'Punt Returns per Game',
  'USFBpuntReturnFairCatchPct': 'Punt Return Fair Catch Percentage',
  'USFBpuntReturnYards': 'Punt Return Yards',
  'USFBpuntReturnYardsPerGame': 'Punt Return Yards per Game',
  'USFByardsPerReturn': 'Yards per Return',
}
export const battingStats = {
  'BSBbattingStrikeouts': 'Batting Strikeouts',
  'BSBrunsBattedIn': 'Runs Batted In',
  'BSBsacrificeHits': 'Sacrifice Hits',
  'BSBHitsTotal': 'Total Hits',
  'BSBwalks': 'Walks',
  'BSBruns': 'Runs',
  'BSBhomeRuns': 'Home Runs',
  'BSBdoubles': 'Doubles',
  'BSBtotalBases': 'Total Bases',
  'BSBextraBaseHits': 'Extra Base Hits',
  'BSBbattingAverage': 'Batting Average',
  'BSBsluggingPercentage': 'Slugging Percentage',
  'BSBonBasePercentage': 'On-Base Percentage',
  'BSBonBasePlusSlugging': 'On-Base Plus Slugging',
  'BSBgroundToFlyRatio': 'Ground to Fly Ratio',
  'BSBatBatsPerHomeRun': 'At-Bats per Home Run',
  'BSBstolenBasePercentage': 'Stolen Base Percentage',
  'BSBbatterWalkToStrikeoutRatio': 'Batter Walk to Strikeout Ratio',
}
export const pitchingStats = {
  'BSBsaves': 'Saves',
  'BSBpitcherStrikeouts': 'Pitcher Strikeouts',
  'BSBhitsGivenUp': 'Hits Given Up',
  'BSBearnedRuns': 'Earned Runs',
  'BSBbattersWalked': 'Batters Walked',
  'BSBrunsAllowed': 'Runs Allowed',
  'BSBhomeRunsAllowed': 'Home Runs Allowed',
  'BSBwins': 'Wins',
  'BSBshutouts': 'Shutouts',
  'BSBearnedRunAverage': 'Earned Run Average',
  'BSBwalksHitsPerInningPitched': 'Walks and Hits per Inning Pitched',
  'BSBwinPct': 'Win Percentage',
  'BSBpitcherCaughtStealingPct': 'Pitcher Caught Stealing Percentage',
  'BSBpitchesPerInning': 'Pitches per Inning',
  'BSBrunSupportAverage': 'Run Support Average',
  'BSBopponentBattingAverage': 'Opponent Batting Average',
  'BSBopponentSlugAverage': 'Opponent Slugging Average',
  'BSBopponentOnBasePct': 'Opponent On-Base Percentage',
  'BSBopponentOnBasePlusSlugging': 'Opponent On-Base Plus Slugging',
  'BSBsavePct': 'Save Percentage',
  'BSBstrikeoutsPerNine': 'Strikeouts per Nine',
  'BSBpitcherStrikeoutToWalkRatio': 'Pitcher Strikeout to Walk Ratio',
}
export const fieldingStats = {
  'BSBdoublePlays': 'Double Plays',
  'BSBerrors': 'Errors',
  'BSBpassedBalls': 'Passed Balls',
  'BSBassists': 'Assists',
  'BSBputouts': 'Putouts',
  'BSBcatcherCaughtStealing': 'Catcher Caught Stealing',
  'BSBcatcherCaughtStealingPct': 'Catcher Caught Stealing Percentage',
  'BSBcatcherStolenBasesAllowed': 'Catcher Stolen Bases Allowed',
  'BSBfieldingPercentage': 'Fielding Percentage',
  'BSBrangeFactor': 'Range Factor',
}
export const penaltyStats = {
  'HKYpimDifferential': 'PIM Differential',
  'HKYpimDifferentialPerGame': 'PIM Differential per Game',
  'HKYtotalPenalties': 'Total Penalties',
  'HKYpenaltiesPerGame': 'Penalties per Game',
  'HKYpenaltyMinutes': 'Penalty Minutes',
  'HKYpenaltyMinutesPerGame': 'Penalty Minutes per Game',
}

export const allStatLabels = {
  'seasonWinLoss': 'Season Win-Loss Record',
  'homeWinLoss': 'Home Win-Loss Record',
  'awayWinLoss': 'Away Win-Loss Record',
  'pointDiff': 'Point Differential',
  'BSKBtotalPoints': 'Total Points',
  'BSKBpointsPerGame': 'Points per Game',
  'BSKBassists': 'Assists',
  'BSKBassistsPerGame': 'Assists per Game',
  'HKYgoals': 'Goals',
  'HKYgoalsPerGame': 'Goals per Game',
  'HKYassists': 'Assists',
  'HKYassistsPerGame': 'Assists per Game',
  'HKYfaceoffs': 'Faceoffs',
  'HKYfaceoffsPerGame': 'Faceoffs per Game',
  'HKYfaceoffsWon': 'Faceoffs Won',
  'HKYfaceoffsWonPerGame': 'Faceoffs Won per Game',
  'HKYfaceoffsLost': 'Faceoffs Lost',
  'HKYfaceoffsLostPerGame': 'Faceoffs Lost per Game',
  'HKYfaceoffPct': 'Faceoff Percentage',
  'HKYfaceoffPctPerGame': 'Faceoff Percentage per Game',
  'USFBtotalFirstDowns': 'Total First Downs',
  'USFBthirdDownEfficiency': 'Third Down Efficiency',
  'USFBpassingYards': 'Passing Yards',
  'USFBreceivingYards': 'Receiving Yards',
  'USFBrushingYards': 'Rushing Yards',
  'USFBsacksPerGame': 'Sacks per Game',
  'USFBfieldGoalsMade': 'Field Goals Made',
  'USFBtotalTouchdowns': 'Total Touchdowns',
  'USFBtouchdownsPerGame': 'Touchdowns per Game',
  'USFBtotalPoints': 'Total Points',
  'USFBpointsPerGame': 'Points per Game',
  'USFBtotalPenyards': 'Total Penalty Yards',
  'USFBaveragePenYardsPerGame': 'Average Penalty Yards per Game',
  'USFBgiveaways': 'Giveaways',
  'USFBtakeaways': 'Takeaways',
  'USFBturnoverDiff': 'Turnover Differential',
  'BSKBassistRatio': 'Assist Ratio',
  'BSKBeffectiveFgPercent': 'Effective Field Goal Percentage',
  'BSKBfieldGoalPercent': 'Field Goal Percentage',
  'BSKBfieldGoalsAttempted': 'Field Goals Attempted',
  'BSKBfieldGoalsMade': 'Field Goals Made',
  'BSKBfieldGoalsPerGame': 'Field Goals per Game',
  'BSKBfreeThrowPercent': 'Free Throw Percentage',
  'BSKBfreeThrowsAttempted': 'Free Throws Attempted',
  'BSKBfreeThrowsMade': 'Free Throws Made',
  'BSKBfreeThrowsMadePerGame': 'Free Throws Made per Game',
  'BSKBoffensiveRebounds': 'Offensive Rebounds',
  'BSKBoffensiveReboundsPerGame': 'Offensive Rebounds per Game',
  'BSKBoffensiveReboundRate': 'Offensive Rebound Rate',
  'BSKBoffensiveTurnovers': 'Offensive Turnovers',
  'BSKBturnoversPerGame': 'Turnovers per Game',
  'BSKBturnoverRatio': 'Turnover Ratio',
  'BSKBthreePointPct': 'Three-Point Percentage',
  'BSKBthreePointsAttempted': 'Three-Point Attempts',
  'BSKBthreePointsMade': 'Three-Point Made',
  'BSKBtrueShootingPct': 'True Shooting Percentage',
  'BSKBpace': 'Pace',
  'BSKBpointsInPaint': 'Points in the Paint',
  'BSKBshootingEfficiency': 'Shooting Efficiency',
  'BSKBscoringEfficiency': 'Scoring Efficiency',
  'HKYshotsIn1st': 'Shots in 1st Period',
  'HKYshotsIn1stPerGame': 'Shots in 1st Period per Game',
  'HKYshotsIn2nd': 'Shots in 2nd Period',
  'HKYshotsIn2ndPerGame': 'Shots in 2nd Period per Game',
  'HKYshotsIn3rd': 'Shots in 3rd Period',
  'HKYshotsIn3rdPerGame': 'Shots in 3rd Period per Game',
  'HKYtotalShots': 'Total Shots',
  'HKYtotalShotsPerGame': 'Total Shots per Game',
  'HKYshotsMissed': 'Shots Missed',
  'HKYshotsMissedPerGame': 'Shots Missed per Game',
  'HKYppgGoals': 'Power Play Goals',
  'HKYppgGoalsPerGame': 'Power Play Goals per Game',
  'HKYppassists': 'Power Play Assists',
  'HKYppassistsPerGame': 'Power Play Assists per Game',
  'HKYpowerplayPct': 'Power Play Percentage',
  'HKYshortHandedGoals': 'Shorthanded Goals',
  'HKYshortHandedGoalsPerGame': 'Shorthanded Goals per Game',
  'HKYshootingPct': 'Shooting Percentage',
  'HKYgiveaways': 'Giveaways',
  'HKYshotDifferential': 'Shot Differential',
  'HKYshotDifferentialPerGame': 'Shot Differential per Game',
  'HKYgoalDifferentialPerGame': 'Goal Differential per Game',
  'BSKBblocks': 'Blocks',
  'BSKBblocksPerGame': 'Blocks per Game',
  'BSKBdefensiveRebounds': 'Defensive Rebounds',
  'BSKBdefensiveReboundsPerGame': 'Defensive Rebounds per Game',
  'BSKBsteals': 'Steals',
  'BSKBstealsPerGame': 'Steals per Game',
  'BSKBreboundRate': 'Rebound Rate',
  'BSKBreboundsPerGame': 'Rebounds per Game',
  'BSKBfoulsPerGame': 'Fouls per Game',
  'BSKBteamAssistToTurnoverRatio': 'Team Assist to Turnover Ratio',
  'HKYgoalsAgainst': 'Goals Against',
  'HKYgoalsAgainstPerGame': 'Goals Against per Game',
  'HKYshotsAgainst': 'Shots Against',
  'HKYshotsAgainstPerGame': 'Shots Against per Game',
  'HKYpenaltyKillPct': 'Penalty Kill Percentage',
  'HKYpenaltyKillPctPerGame': 'Penalty Kill Percentage per Game',
  'HKYppGoalsAgainst': 'Power Play Goals Against',
  'HKYppGoalsAgainstPerGame': 'Power Play Goals Against per Game',
  'HKYshutouts': 'Shutouts',
  'HKYsaves': 'Saves',
  'HKYsavesPerGame': 'Saves per Game',
  'HKYsavePct': 'Save Percentage',
  'HKYblockedShots': 'Blocked Shots',
  'HKYblockedShotsPerGame': 'Blocked Shots per Game',
  'HKYhits': 'Hits',
  'HKYhitsPerGame': 'Hits per Game',
  'HKYtakeaways': 'Takeaways',
  'HKYtakeawaysPerGame': 'Takeaways per Game',
  'USFBtacklesforLoss': 'Tackles for Loss',
  'USFBtacklesforLossPerGame': 'Tackles for Loss per Game',
  'USFBinterceptions': 'Interceptions',
  'USFByardsPerInterception': 'Yards per Interception',
  'USFBsacksTotal': 'Total Sacks',
  'USFBsackYards': 'Sack Yards',
  'USFBsackYardsPerGame': 'Sack Yards per Game',
  'USFBstuffs': 'Stuffs',
  'USFBstuffsPerGame': 'Stuffs per Game',
  'USFBstuffYards': 'Stuff Yards',
  'USFBpassesDefended': 'Passes Defended',
  'USFBpassesDefendedPerGame': 'Passes Defended per Game',
  'USFBsafties': 'Safeties',
  'USFBcompletionPercent': 'Completion Percentage',
  'USFBcompletions': 'Completions',
  'USFBcompletionsPerGame': 'Completions per Game',
  'USFBnetPassingYards': 'Net Passing Yards',
  'USFBnetPassingYardsPerGame': 'Net Passing Yards per Game',
  'USFBpassingFirstDowns': 'Passing First Downs',
  'USFBpassingTouchdowns': 'Passing Touchdowns',
  'USFBpassingYardsPerGame': 'Passing Yards per Game',
  'USFBpassingAttempts': 'Passing Attempts',
  'USFBpassingAttemptsPerGame': 'Passing Attempts per Game',
  'USFByardsPerPassAttempt': 'Yards per Pass Attempt',
  'USFBreceivingFirstDowns': 'Receiving First Downs',
  'USFBreceivingTouchdowns': 'Receiving Touchdowns',
  'USFBreceivingYardsPerGame': 'Receiving Yards per Game',
  'USFBreceivingYardsPerReception': 'Receiving Yards per Reception',
  'USFBreceivingYardsAfterCatch': 'Receiving Yards After Catch',
  'USFBreceivingYardsAfterCatchPerGame': 'Receiving Yards After Catch per Game',
  'USFBrushingAttempts': 'Rushing Attempts',
  'USFBrushingFirstDowns': 'Rushing First Downs',
  'USFBrushingTouchdowns': 'Rushing Touchdowns',
  'USFBrushingYardsPerGame': 'Rushing Yards per Game',
  'USFByardsPerRushAttempt': 'Yards per Rush Attempt',
  'USFBaverageKickoffYards': 'Average Kickoff Yards',
  'USFBaverageKickoffYardsPerGame': 'Average Kickoff Yards per Game',
  'USFBextraPointAttempts': 'Extra Point Attempts',
  'USFBextraPointAttemptsPerGame': 'Extra Point Attempts per Game',
  'USFBextraPointsMade': 'Extra Points Made',
  'USFBextraPointsMadePerGame': 'Extra Points Made per Game',
  'USFBextraPointPercent': 'Extra Point Percentage',
  'USFBextraPointPercentPerGame': 'Extra Point Percentage per Game',
  'USFBfieldGoalAttempts': 'Field Goal Attempts',
  'USFBfieldGoalAttemptsPerGame': 'Field Goal Attempts per Game',
  'USFBfieldGoalsMadePerGame': 'Field Goals Made per Game',
  'USFBfieldGoalPct': 'Field Goal Percentage',
  'USFBfieldGoalPercentPerGame': 'Field Goal Percentage per Game',
  'USFBtouchbacks': 'Touchbacks',
  'USFBtouchbacksPerGame': 'Touchbacks per Game',
  'USFBtouchBackPercentage': 'Touchback Percentage',
  'USFBkickReturns': 'Kick Returns',
  'USFBkickReturnsPerGame': 'Kick Returns per Game',
  'USFBkickReturnYards': 'Kick Return Yards',
  'USFBkickReturnYardsPerGame': 'Kick Return Yards per Game',
  'USFBpuntReturns': 'Punt Returns',
  'USFBpuntReturnsPerGame': 'Punt Returns per Game',
  'USFBpuntReturnFairCatchPct': 'Punt Return Fair Catch Percentage',
  'USFBpuntReturnYards': 'Punt Return Yards',
  'USFBpuntReturnYardsPerGame': 'Punt Return Yards per Game',
  'USFByardsPerReturn': 'Yards per Return',
  'BSBbattingStrikeouts': 'Batting Strikeouts',
  'BSBrunsBattedIn': 'Runs Batted In',
  'BSBsacrificeHits': 'Sacrifice Hits',
  'BSBHitsTotal': 'Total Hits',
  'BSBwalks': 'Walks',
  'BSBruns': 'Runs',
  'BSBhomeRuns': 'Home Runs',
  'BSBdoubles': 'Doubles',
  'BSBtotalBases': 'Total Bases',
  'BSBextraBaseHits': 'Extra Base Hits',
  'BSBbattingAverage': 'Batting Average',
  'BSBsluggingPercentage': 'Slugging Percentage',
  'BSBonBasePercentage': 'On-Base Percentage',
  'BSBonBasePlusSlugging': 'On-Base Plus Slugging',
  'BSBgroundToFlyRatio': 'Ground to Fly Ratio',
  'BSBatBatsPerHomeRun': 'At-Bats per Home Run',
  'BSBstolenBasePercentage': 'Stolen Base Percentage',
  'BSBbatterWalkToStrikeoutRatio': 'Batter Walk to Strikeout Ratio',
  'BSBsaves': 'Saves',
  'BSBpitcherStrikeouts': 'Pitcher Strikeouts',
  'BSBhitsGivenUp': 'Hits Given Up',
  'BSBearnedRuns': 'Earned Runs',
  'BSBbattersWalked': 'Batters Walked',
  'BSBrunsAllowed': 'Runs Allowed',
  'BSBhomeRunsAllowed': 'Home Runs Allowed',
  'BSBwins': 'Wins',
  'BSBshutouts': 'Shutouts',
  'BSBearnedRunAverage': 'Earned Run Average',
  'BSBwalksHitsPerInningPitched': 'Walks and Hits per Inning Pitched',
  'BSBwinPct': 'Win Percentage',
  'BSBpitcherCaughtStealingPct': 'Pitcher Caught Stealing Percentage',
  'BSBpitchesPerInning': 'Pitches per Inning',
  'BSBrunSupportAverage': 'Run Support Average',
  'BSBopponentBattingAverage': 'Opponent Batting Average',
  'BSBopponentSlugAverage': 'Opponent Slugging Average',
  'BSBopponentOnBasePct': 'Opponent On-Base Percentage',
  'BSBopponentOnBasePlusSlugging': 'Opponent On-Base Plus Slugging',
  'BSBsavePct': 'Save Percentage',
  'BSBstrikeoutsPerNine': 'Strikeouts per Nine',
  'BSBpitcherStrikeoutToWalkRatio': 'Pitcher Strikeout to Walk Ratio',
  'BSBdoublePlays': 'Double Plays',
  'BSBerrors': 'Errors',
  'BSBpassedBalls': 'Passed Balls',
  'BSBassists': 'Assists',
  'BSBputouts': 'Putouts',
  'BSBcatcherCaughtStealing': 'Catcher Caught Stealing',
  'BSBcatcherCaughtStealingPct': 'Catcher Caught Stealing Percentage',
  'BSBcatcherStolenBasesAllowed': 'Catcher Stolen Bases Allowed',
  'BSBfieldingPercentage': 'Fielding Percentage',
  'BSBrangeFactor': 'Range Factor',
  'HKYpimDifferential': 'PIM Differential',
  'HKYpimDifferentialPerGame': 'PIM Differential per Game',
  'HKYtotalPenalties': 'Total Penalties',
  'HKYpenaltiesPerGame': 'Penalties per Game',
  'HKYpenaltyMinutes': 'Penalty Minutes',
  'HKYpenaltyMinutesPerGame': 'Penalty Minutes per Game',
}

export const allStatLabelsShort = {
  'seasonWinLoss': 'Win-Loss',
  'homeWinLoss': 'Home W/L',
  'awayWinLoss': 'Away W/L',
  'pointDiff': 'Point Diff',
  'BSKBtotalPoints': 'Total Points',
  'BSKBpointsPerGame': 'Pts per Game',
  'BSKBassists': 'Assists',
  'BSKBassistsPerGame': 'Assists/G',
  'HKYgoals': 'Goals',
  'HKYgoalsPerGame': 'Goals/G',
  'HKYassists': 'Assists',
  'HKYassistsPerGame': 'Assists/G',
  'HKYfaceoffs': 'Faceoffs',
  'HKYfaceoffsPerGame': 'Faceoffs/G',
  'HKYfaceoffsWon': 'Faceoffs Won',
  'HKYfaceoffsWonPerGame': 'Faceoffs Won/G',
  'HKYfaceoffsLost': 'Faceoffs Lost',
  'HKYfaceoffsLostPerGame': 'Faceoffs Lost/G',
  'HKYfaceoffPct': 'Faceoff %',
  'HKYfaceoffPctPerGame': 'Faceoff %/G',
  'USFBtotalFirstDowns': 'Total First Downs',
  'USFBthirdDownEfficiency': '3rd Down Eff.',
  'USFBpassingYards': 'Passing Yds',
  'USFBreceivingYards': 'Receiving Yds',
  'USFBrushingYards': 'Rushing Yds',
  'USFBsacksPerGame': 'Sacks/G',
  'USFBfieldGoalsMade': 'FG Made',
  'USFBtotalTouchdowns': 'Total TDs',
  'USFBtouchdownsPerGame': 'TDs/G',
  'USFBtotalPoints': 'Total Points',
  'USFBpointsPerGame': 'Pts/G',
  'USFBtotalPenyards': 'Total Pen Yds',
  'USFBaveragePenYardsPerGame': 'Avg Pen Yds/G',
  'USFBgiveaways': 'Giveaways',
  'USFBtakeaways': 'Takeaways',
  'USFBturnoverDiff': 'TO Diff',
  'BSKBassistRatio': 'Assist Ratio',
  'BSKBeffectiveFgPercent': 'Eff FG %',
  'BSKBfieldGoalPercent': 'FG %',
  'BSKBfieldGoalsAttempted': 'FG Att',
  'BSKBfieldGoalsMade': 'FG Made',
  'BSKBfieldGoalsPerGame': 'FG/G',
  'BSKBfreeThrowPercent': 'FT %',
  'BSKBfreeThrowsAttempted': 'FT Att',
  'BSKBfreeThrowsMade': 'FT Made',
  'BSKBfreeThrowsMadePerGame': 'FT Made/G',
  'BSKBoffensiveRebounds': 'Off Rebs',
  'BSKBoffensiveReboundsPerGame': 'Off Rebs/G',
  'BSKBoffensiveReboundRate': 'Off Reb Rate',
  'BSKBoffensiveTurnovers': 'Off TOs',
  'BSKBturnoversPerGame': 'TOs/G',
  'BSKBturnoverRatio': 'TO Ratio',
  'BSKBthreePointPct': '3PT %',
  'BSKBthreePointsAttempted': '3PT Att',
  'BSKBthreePointsMade': '3PT Made',
  'BSKBtrueShootingPct': 'TS %',
  'BSKBpace': 'Pace',
  'BSKBpointsInPaint': 'Pts in Paint',
  'BSKBshootingEfficiency': 'Shoot Eff.',
  'BSKBscoringEfficiency': 'Score Eff.',
  'HKYshotsIn1st': '1st Period Shots',
  'HKYshotsIn1stPerGame': '1st Period Shots/G',
  'HKYshotsIn2nd': '2nd Period Shots',
  'HKYshotsIn2ndPerGame': '2nd Period Shots/G',
  'HKYshotsIn3rd': '3rd Period Shots',
  'HKYshotsIn3rdPerGame': '3rd Period Shots/G',
  'HKYtotalShots': 'Total Shots',
  'HKYtotalShotsPerGame': 'Shots/G',
  'HKYshotsMissed': 'Shots Missed',
  'HKYshotsMissedPerGame': 'Shots Missed/G',
  'HKYppgGoals': 'PP Goals',
  'HKYppgGoalsPerGame': 'PP Goals/G',
  'HKYppassists': 'PP Assists',
  'HKYppassistsPerGame': 'PP Assists/G',
  'HKYpowerplayPct': 'PP %',
  'HKYshortHandedGoals': 'SH Goals',
  'HKYshortHandedGoalsPerGame': 'SH Goals/G',
  'HKYshootingPct': 'Shoot %',
  'HKYgiveaways': 'Giveaways',
  'HKYshotDifferential': 'Shot Diff',
  'HKYshotDifferentialPerGame': 'Shot Diff/G',
  'HKYgoalDifferentialPerGame': 'Goal Diff/G',
  'BSKBblocks': 'Blocks',
  'BSKBblocksPerGame': 'Blocks/G',
  'BSKBdefensiveRebounds': 'Def Rebs',
  'BSKBdefensiveReboundsPerGame': 'Def Rebs/G',
  'BSKBsteals': 'Steals',
  'BSKBstealsPerGame': 'Steals/G',
  'BSKBreboundRate': 'Reb Rate',
  'BSKBreboundsPerGame': 'Rebs/G',
  'BSKBfoulsPerGame': 'Fouls/G',
  'BSKBteamAssistToTurnoverRatio': 'Assist/TO',
  'HKYgoalsAgainst': 'GA',
  'HKYgoalsAgainstPerGame': 'GA/G',
  'HKYshotsAgainst': 'Shots Against',
  'HKYshotsAgainstPerGame': 'Shots Against/G',
  'HKYpenaltyKillPct': 'PK %',
  'HKYpenaltyKillPctPerGame': 'PK %/G',
  'HKYppGoalsAgainst': 'PP GA',
  'HKYppGoalsAgainstPerGame': 'PP GA/G',
  'HKYshutouts': 'Shutouts',
  'HKYsaves': 'Saves',
  'HKYsavesPerGame': 'Saves/G',
  'HKYsavePct': 'Save %',
  'HKYblockedShots': 'Blocked Shots',
  'HKYblockedShotsPerGame': 'Blocked Shots/G',
  'HKYhits': 'Hits',
  'HKYhitsPerGame': 'Hits/G',
  'HKYtakeaways': 'Takeaways',
  'HKYtakeawaysPerGame': 'Takeaways/G',
  'USFBtacklesforLoss': 'TFL',
  'USFBtacklesforLossPerGame': 'TFL/G',
  'USFBinterceptions': 'INTs',
  'USFByardsPerInterception': 'Yds/INT',
  'USFBsacksTotal': 'Total Sacks',
  'USFBsackYards': 'Sack Yds',
  'USFBsackYardsPerGame': 'Sack Yds/G',
  'USFBstuffs': 'Stuffs',
  'USFBstuffsPerGame': 'Stuffs/G',
  'USFBstuffYards': 'Stuff Yds',
  'USFBpassesDefended': 'PD',
  'USFBpassesDefendedPerGame': 'PD/G',
  'USFBsafties': 'Safeties',
  'USFBcompletionPercent': 'Comp %',
  'USFBcompletions': 'Completions',
  'USFBcompletionsPerGame': 'Completions/G',
  'USFBnetPassingYards': 'Net Pass Yds',
  'USFBnetPassingYardsPerGame': 'Net Pass Yds/G',
  'USFBpassingFirstDowns': 'Pass FD',
  'USFBpassingTouchdowns': 'Pass TDs',
  'USFBpassingYardsPerGame': 'Pass Yds/G',
  'USFBpassingAttempts': 'Pass Att',
  'USFBpassingAttemptsPerGame': 'Pass Att/G',
  'USFByardsPerPassAttempt': 'Yds/Pass Att',
  'USFBreceivingFirstDowns': 'Rec FD',
  'USFBreceivingTouchdowns': 'Rec TDs',
  'USFBreceivingYardsPerGame': 'Rec Yds/G',
  'USFBreceivingYardsPerReception': 'Rec Yds/Rec',
  'USFBreceivingYardsAfterCatch': 'YAC Yds',
  'USFBreceivingYardsAfterCatchPerGame': 'YAC Yds/G',
  'USFBrushingAttempts': 'Rush Att',
  'USFBrushingFirstDowns': 'Rush FD',
  'USFBrushingTouchdowns': 'Rush TDs',
  'USFBrushingYardsPerGame': 'Rush Yds/G',
  'USFByardsPerRushAttempt': 'Yds/Rush',
  'USFBaverageKickoffYards': 'Avg KO Yds',
  'USFBaverageKickoffYardsPerGame': 'Avg KO Yds/G',
  'USFBextraPointAttempts': 'XP Att',
  'USFBextraPointAttemptsPerGame': 'XP Att/G',
  'USFBextraPointsMade': 'XP Made',
  'USFBextraPointsMadePerGame': 'XP Made/G',
  'USFBextraPointPercent': 'XP %',
  'USFBextraPointPercentPerGame': 'XP %/G',
  'USFBfieldGoalAttempts': 'FG Att',
  'USFBfieldGoalAttemptsPerGame': 'FG Att/G',
  'USFBfieldGoalsMadePerGame': 'FG Made/G',
  'USFBfieldGoalPct': 'FG %',
  'USFBfieldGoalPercentPerGame': 'FG %/G',
  'USFBtouchbacks': 'Touchbacks',
  'USFBtouchbacksPerGame': 'Touchbacks/G',
  'USFBtouchBackPercentage': 'TB %',
  'USFBkickReturns': 'Kick Returns',
  'USFBkickReturnsPerGame': 'Kick Returns/G',
  'USFBkickReturnYards': 'KR Yds',
  'USFBkickReturnYardsPerGame': 'KR Yds/G',
  'USFBpuntReturns': 'Punt Returns',
  'USFBpuntReturnsPerGame': 'Punt Returns/G',
  'USFBpuntReturnFairCatchPct': 'PR Fair Catch %',
  'USFBpuntReturnYards': 'PR Yds',
  'USFBpuntReturnYardsPerGame': 'PR Yds/G',
  'USFByardsPerReturn': 'Yds/Return',
  'BSBbattingStrikeouts': 'K\'s',
  'BSBrunsBattedIn': 'RBIs',
  'BSBsacrificeHits': 'Sac Hits',
  'BSBHitsTotal': 'Hits',
  'BSBwalks': 'Walks',
  'BSBruns': 'Runs',
  'BSBhomeRuns': 'HRs',
  'BSBdoubles': '2B',
  'BSBtotalBases': 'TB',
  'BSBextraBaseHits': 'XBH',
  'BSBbattingAverage': 'Avg',
  'BSBsluggingPercentage': 'SLG',
  'BSBonBasePercentage': 'OBP',
  'BSBonBasePlusSlugging': 'OPS',
  'BSBgroundToFlyRatio': 'GB/FB Ratio',
  'BSBatBatsPerHomeRun': 'AB/HR',
  'BSBstolenBasePercentage': 'SB %',
  'BSBbatterWalkToStrikeoutRatio': 'BB/K Ratio',
  'BSBsaves': 'Saves',
  'BSBpitcherStrikeouts': 'K\'s',
  'BSBhitsGivenUp': 'Hits Allowed',
  'BSBearnedRuns': 'ERs',
  'BSBbattersWalked': 'BBs',
  'BSBrunsAllowed': 'Runs Allowed',
  'BSBhomeRunsAllowed': 'HR Allowed',
  'BSBwins': 'Wins',
  'BSBshutouts': 'Shutouts',
  'BSBearnedRunAverage': 'ERA',
  'BSBwalksHitsPerInningPitched': 'WHIP',
  'BSBwinPct': 'Win %',
  'BSBpitcherCaughtStealingPct': 'CS %',
  'BSBpitchesPerInning': 'Pitches/Inning',
  'BSBrunSupportAverage': 'RS Avg',
  'BSBopponentBattingAverage': 'Opponent Avg',
  'BSBopponentSlugAverage': 'Opponent SLG',
  'BSBopponentOnBasePct': 'Opponent OBP',
  'BSBopponentOnBasePlusSlugging': 'Opponent OPS',
  'BSBsavePct': 'Save %',
  'BSBstrikeoutsPerNine': 'K/9',
  'BSBpitcherStrikeoutToWalkRatio': 'K/BB Ratio',
  'BSBdoublePlays': 'DPs',
  'BSBerrors': 'Errors',
  'BSBpassedBalls': 'PBs',
  'BSBassists': 'Assists',
  'BSBputouts': 'Putouts',
  'BSBcatcherCaughtStealing': 'Catcher CS',
  'BSBcatcherCaughtStealingPct': 'Catcher CS %',
  'BSBcatcherStolenBasesAllowed': 'Catcher SBA',
  'BSBfieldingPercentage': 'Fld %',
  'BSBrangeFactor': 'Range Factor',
  'HKYpimDifferential': 'PIM Diff',
  'HKYpimDifferentialPerGame': 'PIM Diff/G',
  'HKYtotalPenalties': 'Total Penalties',
  'HKYpenaltiesPerGame': 'Penalties/G',
  'HKYpenaltyMinutes': 'PIM',
  'HKYpenaltyMinutesPerGame': 'PIM/G',
}


export const isSameDay = (date1, date2) => {
  const d1 = new Date(date1);
  const d2 = new Date(date2);

  return d1.getFullYear() === d2.getFullYear() &&
    d1.getMonth() === d2.getMonth() &&
    d1.getDate() === d2.getDate();
};

// Helper function to format Date as 'YYYY-MM-DD'
export const formatDate = (date) => {
  const d = new Date(date);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0'); // getMonth is zero-based
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

// Calculate the index difference
export const indexCondition = (game, indexDifSmall, indexDiffRange) => {

  const indexDiff = game.predictedWinner === 'home'
    ? Math.abs(game.homeTeamScaledIndex - game.awayTeamScaledIndex)
    : Math.abs(game.awayTeamScaledIndex - game.homeTeamScaledIndex);
  return indexDiff >= indexDifSmall && (indexDiff <= (indexDifSmall + indexDiffRange));
};

export const strengthCondition = (game, confidenceLow, confidenceRange) => {
  return game.predictionStrength > confidenceLow && game.predictionStrength < (confidenceLow + confidenceRange);
};

export const probabilityCondition = (o, game, sportsbook) => {
  return (o.impliedProb * 100) < (game.winPercent) 
};



// You can also combine them into a single condition
export const combinedCondition = (game, o, indexDifSmall, indexDiffRange, confidenceLow, confidenceRange, sportsbook) => {

  return probabilityCondition(o, game, sportsbook)
    && indexCondition(game, indexDifSmall, indexDiffRange)
    && strengthCondition(game, confidenceLow, confidenceRange)
};


export const valueBetConditionCheck = (sports, game, sportsbook, pastGames) => {
  const bookmaker = game.bookmakers.find(bookmaker => bookmaker.key === sportsbook);
  if (bookmaker) {
    const marketData = bookmaker?.markets?.find(m => m.key === 'h2h');

    let outcome = marketData?.outcomes?.find(o => {
      return o.name === (game.predictedWinner === 'home' ? game.home_team : game.away_team)
    });

    if (outcome) {
      let currentSport = sports.find(arraySport => arraySport.name === game.sport_key)
      let sportSettings = currentSport?.valueBetSettings.find((setting) => setting.bookmaker === sportsbook)
      if (sportSettings !== undefined) {
        return combinedCondition(game, outcome, sportSettings.settings.indexDiffSmallNum, sportSettings.settings.indexDiffRangeNum, sportSettings.settings.confidenceLowNum, sportSettings.settings.confidenceRangeNum, sportsbook)
      }

    }
  }
}

