const americanfootball_ncaaf_stats = [
    "seasonWinLoss",
    "homeWinLoss",
    "awayWinLoss",
    "pointDiff",
    "gamesPlayed",
    "netTotalYards",
    "netYardsPerGame",
    "totalOffensivePlays",
    "totalYards",
    "totalYardsFromScrimmage",
    "yardsFromScrimmagePerGame",
    "yardsPerGame",
    "longRushing",
    "rushingAttempts",
    "firstDowns",
    "firstDownsPerGame",
    "passingAttempts",
    "possessionTimeSeconds",
    "thirdDownAttempts",
    "rushingYards",
    "rushingYardsPerGame",
    "yardsPerRushAttempt",
    "netPassingYards",
    "netPassingYardsPerGame",
    "netYardsPerPassAttempt",
    "ESPNWRRating",
    "receptions",
    "completionPct",
    "completions",
    "receivingYards",
    "receivingYardsAtCatch",
    "receivingYardsPerGame",
    "yardsPerReception",
    "passingYards",
    "passingYardsAtCatch",
    "passingYardsPerGame",
    "yardsPerCompletion",
    "yardsPerPassAttempt",
    "ESPNRBRating",
    "longReception",
    "ESPNQBRating",
    "longPassing",
    "firstDownsPassing",
    "firstDownsRushing",
    "kickoffs",
    "totalPenalties",
    "totalPenaltyYards",
    "thirdDownConvPct",
    "thirdDownConvs",
    "yardsAllowed",
    "punts",
    "grossAvgPuntYards",
    "puntYards",
    "longPunt",
    "totalPoints",
    "totalPointsPerGame",
    "sacks",
    "totalKickingPoints",
    "totalTouchdowns",
    "totalDrives",
    "yardsPerReturn",
    "extraPointAttempts",
    "kickExtraPoints",
    "kickExtraPointsMade",
    "extraPointPct",
    "extraPointsMade",
    "totalTackles",
    "soloTackles",
    "assistTackles",
    "tacklesForLoss",
    "kickReturns",
    "passesDefended",
    "kickReturnYards",
    "longKickReturn",
    "fourthDownAttempts",
    "kickoffReturns",
    "interceptions",
    "avgKickoffReturnYards",
    "touchbacks",
    "touchbackPct",
    "avgSackYards",
    "firstDownsPenalty",
    "passingTouchdowns",
    "sackYardsLost",
    "receivingTouchdowns",
    "passingTouchdownPct",
    "sackYards",
    "rushingTouchdowns",
    "fieldGoalAttempts",
    "puntReturns",
    "puntsInside20",
    "puntsInside20Pct",
    "hurries",
    "fumbles",
    "fieldGoalPct",
    "fieldGoalsMade",
    "fieldGoals",
    "fourthDownConvs",
    "fourthDownConvPct",
    "turnOverDifferential",
]

const americanfootball_ncaaf_general_stats = ['gamesPlayed', 'fumbles', 'totalPoints', 'totalPointsPerGame', 'totalTouchdowns', 'kickExtraPoints', 'kickExtraPointsMade', 'fieldGoals']
const americanfootball_ncaaf_passing_stats = ['netTotalYards', 'netYardsPerGame', 'totalOffensivePlays', 'totalYards', 'totalYardsFromScrimmage', 'yardsFromScrimmagePerGame', 'yardsPerGame', 'passingAttempts', 'netPassingYards', 'netPassingYardsPerGame', 'netYardsPerPassAttempt', 'completionPct', 'completions', 'passingYards', 'passingYardsAtCatch', 'passingYardsPerGame', 'yardsPerCompletion', 'yardsPerPassAttempt', 'ESPNQBRating', 'longPassing', 'qb_sacks', 'interceptions', 'passingTouchdowns', 'sackYardsLost', 'passingTouchdownPct']
const americanfootball_ncaaf_receiving_stats = ['ESPNWRRating', 'receptions', 'receivingYards', 'receivingYardsAtCatch', 'receivingYardsPerGame', 'yardsPerReception', 'longReception', 'receivingTouchdowns']
const americanfootball_ncaaf_rushing_stats = ['longRushing', 'rushingAttempts', 'rushingYards', 'rushingYardsPerGame', 'yardsPerRushAttempt', 'ESPNRBRating', 'rushingTouchdowns']
const americanfootball_ncaaf_defensive_stats = ['yardsAllowed', 'sacks', 'totalTackles', 'soloTackles', 'assistTackles', 'tacklesForLoss', 'passesDefended', 'avgSackYards', 'sackYards', 'hurries', 'defensive_interceptions']
const americanfootball_ncaaf_special_teams_stats = ['kickoffs', 'totalKickingPoints', 'extraPointAttempts', 'extraPointPct', 'extraPointsMade', 'kickoffReturns', 'touchbacks', 'touchbackPct', 'fieldGoalAttempts', 'fieldGoalPct', 'fieldGoalsMade', 'punts', 'grossAvgPuntYards', 'puntYards', 'longPunt', 'touchbacks_punting', 'touchbackPct_punting', 'puntsInside20', 'puntsInside20Pct', 'yardsPerReturn', 'kickReturns', 'kickReturnYards', 'longKickReturn', 'avgKickoffReturnYards', 'puntReturns']
const americanfootball_ncaaf_miscellaneous_stats = ['firstDowns', 'firstDownsPerGame', 'possessionTimeSeconds', 'thirdDownAttempts', 'firstDownsPassing', 'firstDownsRushing', 'totalPenalties', 'totalPenaltyYards', 'thirdDownConvPct', 'thirdDownConvs', 'totalDrives', 'fourthDownAttempts', 'firstDownsPenalty', 'fourthDownConvs', 'fourthDownConvPct', 'turnOverDifferential']

const americanfootball_nfl_stats = [
    "seasonWinLoss",
    "homeWinLoss",
    "awayWinLoss",
    "pointDiff",
    "gamesPlayed",
    "completionPct",
    "completions",
    "ESPNQBRating",
    "longPassing",
    "netPassingYards",
    "netPassingYardsPerGame",
    "netTotalYards",
    "netYardsPerGame",
    "passingAttempts",
    "passingYards",
    "passingYardsAtCatch",
    "passingYardsPerGame",
    "netPassingAttempts",
    "totalOffensivePlays",
    "totalYards",
    "totalYardsFromScrimmage",
    "yardsFromScrimmagePerGame",
    "yardsPerCompletion",
    "yardsPerGame",
    "yardsPerPassAttempt",
    "netYardsPerPassAttempt",
    "ESPNRBRating",
    "longRushing",
    "rushingAttempts",
    "rushingYards",
    "rushingYardsPerGame",
    "yardsPerRushAttempt",
    "ESPNWRRating",
    "longReception",
    "receivingTargets",
    "receivingYards",
    "receivingYardsAfterCatch",
    "receivingYardsPerGame",
    "receptions",
    "yardsPerReception",
    "assistTackles",
    "soloTackles",
    "totalTackles",
    "yardsAllowed",
    "kickoffs",
    "firstDowns",
    "firstDownsPerGame",
    "possessionTimeSeconds",
    "thirdDownAttempts",
    "totalDrives",
    "receivingYardsAtCatch",
    "firstDownsPassing",
    "totalPenalties",
    "totalPenaltyYards",
    "rushingFirstDowns",
    "firstDownsRushing",
    "thirdDownConvPct",
    "thirdDownConvs",
    "totalPoints",
    "totalPointsPerGame",
    "pointsAllowed",
    "sacks",
    "tacklesForLoss",
    "punts",
    "grossAvgPuntYards",
    "longPunt",
    "puntYards",
    "totalKickingPoints",
    "stuffs",
    "passesDefended",
    "yardsPerReturn",
    "puntReturns",
    "totalTouchdowns",
    "puntReturnYards",
    "touchbackPct",
    "touchbacks",
    "extraPointAttempts",
    "avgPuntReturnYards",
    "extraPointPct",
    "extraPointsMade",
    "kickExtraPoints",
    "kickExtraPointsMade",
    "fieldGoalAttempts",
    "fieldGoalAttemptYards",
    "twoPointRecConvs",
    "sackYardsLost",
    "avgSackYards",
    "sackYards",
    "passingFirstDowns",
    "fieldGoalsMadeYards",
    "longFieldGoalMade",
    "fieldGoalPct",
    "fieldGoalsMade",
    "fieldGoals",
    "firstDownsPenalty",
    "avgKickoffYards",
    "kickoffYards",
    "passingTouchdownPct",
    "passingTouchdowns",
    "receivingTouchdowns",
    "interceptions",
    "kickoffReturns",
    "kickReturns",
    "puntsInside20",
    "puntsInside20Pct",
    "avgKickoffReturnYards",
    "kickoffReturnYards",
    "kickReturnYards",
    "longKickReturn",
    "yardsPerPuntReturn",
    "longPuntReturn",
    "rushingTouchdowns",
    "turnOverDifferential",
]

const americanfootball_nfl_general_stats = ['gamesPlayed', 'totalPoints', 'totalPointsPerGame', 'totalTouchdowns', 'kickExtraPoints', 'kickExtraPointsMade', 'fieldGoals']
const americanfootball_nfl_passing_stats = ['completionPct', 'completions', 'ESPNQBRating', 'longPassing', 'netPassingYards', 'netPassingYardsPerGame', 'netTotalYards', 'netYardsPerGame', 'passingAttempts', 'passingYards', 'passingYardsAtCatch', 'passingYardsPerGame', 'netPassingAttempts', 'totalOffensivePlays', 'totalYards', 'totalYardsFromScrimmage', 'yardsFromScrimmagePerGame', 'yardsPerCompletion', 'yardsPerGame', 'yardsPerPassAttempt', 'netYardsPerPassAttempt', 'sackYardsLost', 'passingFirstDowns', 'passingTouchdownPct', 'passingTouchdowns', 'interceptions']
const americanfootball_nfl_receiving_stats = ['ESPNWRRating', 'longReception', 'receivingTargets', 'receivingYards', 'receivingYardsAfterCatch', 'receivingYardsPerGame', 'receptions', 'yardsPerReception', 'receivingYardsAtCatch', 'twoPointRecConvs', 'receivingTouchdowns']
const americanfootball_nfl_rushing_stats = ['ESPNRBRating', 'longRushing', 'rushingAttempts', 'rushingYards', 'rushingYardsPerGame', 'yardsPerRushAttempt', 'rushingFirstDowns', 'rushingTouchdowns']
const americanfootball_nfl_defensive_stats = ['assistTackles', 'soloTackles', 'totalTackles', 'yardsAllowed', 'pointsAllowed', 'sacks', 'tacklesForLoss', 'stuffs', 'passesDefended', 'avgSackYards', 'sackYards', 'defensive_interceptions']
const americanfootball_nfl_special_teams_stats = ['kickoffs', 'totalKickingPoints', 'touchbackPct', 'touchbacks', 'extraPointAttempts', 'extraPointPct', 'extraPointsMade', 'fieldGoalAttempts', 'fieldGoalAttemptYards', 'fieldGoalsMadeYards', 'longFieldGoalMade', 'fieldGoalPct', 'fieldGoalsMade', 'avgKickoffYards', 'kickoffYards', 'kickoffReturns', 'avgKickoffReturnYards', 'kickoffReturnYards', 'punts', 'grossAvgPuntYards', 'longPunt', 'puntYards', 'puntReturns', 'puntReturnYards', 'touchbacks_punting', 'touchbackPct_punting', 'avgPuntReturnYards', 'puntsInside20', 'puntsInside20Pct', 'yardsPerReturn', 'kickReturns', 'kickReturnYards', 'longKickReturn', 'yardsPerPuntReturn', 'longPuntReturn']
const americanfootball_nfl_miscellaneous_stats = ['firstDowns', 'firstDownsPerGame', 'possessionTimeSeconds', 'thirdDownAttempts', 'totalDrives', 'firstDownsPassing', 'totalPenalties', 'totalPenaltyYards', 'firstDownsRushing', 'thirdDownConvPct', 'thirdDownConvs', 'firstDownsPenalty', 'turnOverDifferential']

const basketball_nba_stats = [
    "seasonWinLoss",
    "homeWinLoss",
    "awayWinLoss",
    "pointDiff",
    "defensiveRebounds",
    "avgDefensiveRebounds",
    "fouls",
    "rebounds",
    "NBARating",
    "avgRebounds",
    "avgFouls",
    "assistTurnoverRatio",
    "totalRebounds",
    "gamesPlayed",
    "assists",
    "fieldGoals",
    "fieldGoalsAttempted",
    "fieldGoalsMade",
    "fieldGoalPct",
    "points",
    "turnovers",
    "threePointPct",
    "threePointFieldGoalsAttempted",
    "threePointFieldGoalsMade",
    "pointsInPaint",
    "avgFieldGoalsMade",
    "avgFieldGoalsAttempted",
    "avgThreePointFieldGoalsMade",
    "avgThreePointFieldGoalsAttempted",
    "avgPoints",
    "avgAssists",
    "avgTurnovers",
    "estimatedPossessions",
    "avgEstimatedPossessions",
    "pointsPerEstimatedPossessions",
    "threePointFieldGoalPct",
    "twoPointFieldGoalsMade",
    "twoPointFieldGoalsAttempted",
    "avgTwoPointFieldGoalsMade",
    "avgTwoPointFieldGoalsAttempted",
    "twoPointFieldGoalPct",
    "shootingEfficiency",
    "scoringEfficiency",
    "freeThrowPct",
    "freeThrowsAttempted",
    "freeThrowsMade",
    "avgFreeThrowsMade",
    "avgFreeThrowsAttempted",
    "offensiveRebounds",
    "avgOffensiveRebounds",
    "offensiveReboundPct",
    "totalTurnovers",
    "avgTotalTurnovers",
    "turnoverPoints",
    "steals",
    "avgSteals",
    "stealFoulRatio",
    "stealTurnoverRatio",
    "fastBreakPoints",
    "blocks",
    "avgBlocks",
    "blockFoulRatio",
]

const basketball_nba_general_stats = ['fouls', 'rebounds', 'NBARating', 'avgRebounds', 'avgFouls', 'assistTurnoverRatio', 'totalRebounds', 'gamesPlayed', 'stealFoulRatio', 'stealTurnoverRatio', 'blockFoulRatio']
const basketball_nba_offensive_stats = ['assists', 'fieldGoals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalPct', 'points', 'turnovers', 'threePointPct', 'threePointFieldGoalsAttempted', 'threePointFieldGoalsMade', 'pointsInPaint', 'avgFieldGoalsMade', 'avgFieldGoalsAttempted', 'avgThreePointFieldGoalsMade', 'avgThreePointFieldGoalsAttempted', 'avgPoints', 'avgAssists', 'avgTurnovers', 'estimatedPossessions', 'avgEstimatedPossessions', 'pointsPerEstimatedPossessions', 'threePointFieldGoalPct', 'twoPointFieldGoalsMade', 'twoPointFieldGoalsAttempted', 'avgTwoPointFieldGoalsMade', 'avgTwoPointFieldGoalsAttempted', 'twoPointFieldGoalPct', 'shootingEfficiency', 'scoringEfficiency', 'freeThrowPct', 'freeThrowsAttempted', 'freeThrowsMade', 'avgFreeThrowsMade', 'avgFreeThrowsAttempted', 'offensiveRebounds', 'avgOffensiveRebounds', 'offensiveReboundPct', 'totalTurnovers', 'avgTotalTurnovers', 'fastBreakPoints']
const basketball_nba_defensive_stats = ['defensiveRebounds', 'avgDefensiveRebounds', 'turnoverPoints', 'steals', 'avgSteals', 'blocks', 'avgBlocks']

const basketball_ncaab_stats = [
    "seasonWinLoss",
    "homeWinLoss",
    "awayWinLoss",
    "pointDiff",
    "defensiveRebounds",
    "avgDefensiveRebounds",
    "fouls",
    "rebounds",
    "avgRebounds",
    "totalRebounds",
    "gamesPlayed",
    "assists",
    "fieldGoals",
    "fieldGoalsAttempted",
    "fieldGoalsMade",
    "fieldGoalPct",
    "points",
    "threePointFieldGoalsAttempted",
    "avgFieldGoalsMade",
    "avgFieldGoalsAttempted",
    "avgThreePointFieldGoalsAttempted",
    "avgPoints",
    "avgAssists",
    "estimatedPossessions",
    "avgEstimatedPossessions",
    "pointsPerEstimatedPossessions",
    "twoPointFieldGoalsMade",
    "twoPointFieldGoalsAttempted",
    "avgTwoPointFieldGoalsMade",
    "avgTwoPointFieldGoalsAttempted",
    "twoPointFieldGoalPct",
    "shootingEfficiency",
    "scoringEfficiency",
    "assistTurnoverRatio",
    "turnovers",
    "totalTurnovers",
    "avgTurnovers",
    "avgTotalTurnovers",
    "freeThrowsAttempted",
    "avgFreeThrowsAttempted",
    "offensiveRebounds",
    "avgOffensiveRebounds",
    "offensiveReboundPct",
    "freeThrowPct",
    "freeThrowsMade",
    "avgFreeThrowsMade",
    "threePointFieldGoalsMade",
    "avgThreePointFieldGoalsMade",
    "threePointFieldGoalPct",
    "steals",
    "avgSteals",
    "stealFoulRatio",
    "stealTurnoverRatio",
    "turnoverPoints",
    "blocks",
    "avgBlocks",
    "blockFoulRatio",
    "fastBreakPoints"
]

const basketball_ncaab_general_stats = ['fouls', 'avgFouls', 'rebounds', 'avgRebounds', 'totalRebounds', 'gamesPlayed', 'stealTurnoverRatio', 'blockFoulRatio']
const basketball_ncaab_offensive_stats = ['assists', 'fieldGoals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalPct', 'points', 'threePointFieldGoalsAttempted', 'avgFieldGoalsMade', 'avgFieldGoalsAttempted', 'avgThreePointFieldGoalsAttempted', 'avgPoints', 'avgAssists', 'estimatedPossessions', 'avgEstimatedPossessions', 'pointsPerEstimatedPossessions', 'twoPointFieldGoalsMade', 'twoPointFieldGoalsAttempted', 'avgTwoPointFieldGoalsMade', 'avgTwoPointFieldGoalsAttempted', 'twoPointFieldGoalPct', 'shootingEfficiency', 'scoringEfficiency', 'assistTurnoverRatio', 'turnovers', 'totalTurnovers', 'avgTurnovers', 'avgTotalTurnovers', 'freeThrowsAttempted', 'avgFreeThrowsAttempted', 'offensiveRebounds', 'avgOffensiveRebounds', 'offensiveReboundPct', 'freeThrowPct', 'freeThrowsMade', 'avgFreeThrowsMade', 'threePointFieldGoalsMade', 'avgThreePointFieldGoalsMade', 'threePointFieldGoalPct', 'fastBreakPoints']
const basketball_ncaab_defensive_stats = ['defensiveRebounds', 'avgDefensiveRebounds', 'steals', 'avgSteals', 'stealFoulRatio', 'turnoverPoints', 'blocks', 'avgBlocks']

const basketball_wncaab_stats = [
    "seasonWinLoss",
    "homeWinLoss",
    "awayWinLoss",
    "pointDiff",
    "defensiveRebounds",
    "avgDefensiveRebounds",
    "fouls",
    "rebounds",
    "avgRebounds",
    "avgFouls",
    "totalRebounds",
    "gamesPlayed",
    "fieldGoals",
    "fieldGoalsAttempted",
    "fieldGoalsMade",
    "fieldGoalPct",
    "points",
    "turnovers",
    "totalTurnovers",
    "avgFieldGoalsMade",
    "avgFieldGoalsAttempted",
    "avgPoints",
    "avgTurnovers",
    "estimatedPossessions",
    "avgEstimatedPossessions",
    "pointsPerEstimatedPossessions",
    "avgTotalTurnovers",
    "twoPointFieldGoalsMade",
    "twoPointFieldGoalsAttempted",
    "avgTwoPointFieldGoalsMade",
    "avgTwoPointFieldGoalsAttempted",
    "twoPointFieldGoalPct",
    "shootingEfficiency",
    "scoringEfficiency",
    "threePointFieldGoalsAttempted",
    "avgThreePointFieldGoalsAttempted",
    "assistTurnoverRatio",
    "assists",
    "avgAssists",
    "offensiveRebounds",
    "avgOffensiveRebounds",
    "offensiveReboundPct",
    "freeThrowsAttempted",
    "avgFreeThrowsAttempted",
    "freeThrowPct",
    "freeThrowsMade",
    "avgFreeThrowsMade",
    "steals",
    "avgSteals",
    "stealFoulRatio",
    "stealTurnoverRatio",
    "threePointFieldGoalsMade",
    "avgThreePointFieldGoalsMade",
    "threePointFieldGoalPct",
    "turnoverPoints",
    "blocks",
    "avgBlocks",
    "blockFoulRatio",
    "fastBreakPoints"
]

const basketball_wncaab_general_stats = ['fouls', 'rebounds', 'avgRebounds', 'avgFouls', 'totalRebounds', 'gamesPlayed', 'assistTurnoverRatio', 'stealFoulRatio', 'stealTurnoverRatio']
const basketball_wncaab_offensive_stats = ['fieldGoals', 'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalPct', 'points', 'turnovers', 'totalTurnovers', 'avgFieldGoalsMade', 'avgFieldGoalsAttempted', 'avgPoints', 'avgTurnovers', 'estimatedPossessions', 'avgEstimatedPossessions', 'pointsPerEstimatedPossessions', 'avgTotalTurnovers', 'twoPointFieldGoalsMade', 'twoPointFieldGoalsAttempted', 'avgTwoPointFieldGoalsMade', 'avgTwoPointFieldGoalsAttempted', 'twoPointFieldGoalPct', 'shootingEfficiency', 'scoringEfficiency', 'threePointFieldGoalsAttempted', 'avgThreePointFieldGoalsAttempted', 'assists', 'avgAssists', 'offensiveRebounds', 'avgOffensiveRebounds', 'offensiveReboundPct', 'freeThrowsAttempted', 'avgFreeThrowsAttempted', 'freeThrowPct', 'freeThrowsMade', 'avgFreeThrowsMade', 'threePointFieldGoalsMade', 'avgThreePointFieldGoalsMade', 'threePointFieldGoalPct', 'fastBreakPoints']
const basketball_wncaab_defensive_stats = ['defensiveRebounds', 'avgDefensiveRebounds', 'steals', 'avgSteals', 'turnoverPoints', 'blocks', 'avgBlocks', 'blockFoulRatio']

const icehockey_nhl_stats = [
    "seasonWinLoss",
    "homeWinLoss",
    "awayWinLoss",
    "pointDiff",
    "shotsAgainst",
    "saves",
    "savePct",
    "blockedShots",
    "hits",
    "shifts",
    "shotsTotal",
    "shotsMissed",
    "pointsPerGame",
    "totalFaceOffs",
    "faceoffsWon",
    "faceoffsLost",
    "faceoffPercent",
    "shotsIn1stPeriod",
    "shotsIn2ndPeriod",
    "shotsIn3rdPeriod",
    "giveaways",
    "takeaways",
    "penalties",
    "penaltyMinutes",
    "timesShortHanded",
    "powerPlayOpportunities",
    "shotDifferential",
    "goalsAgainst",
    "points",
    "goals",
    "shootingPct",
    "penaltyKillPct",
    "assists",
    "goalDifferential",
    "PIMDifferential",
    "powerPlayAssists",
    "powerPlayGoalsAgainst",
    "powerPlayGoals",
    "powerPlayPct",
]

const icehockey_nhl_general_stats = ['shifts', 'shotDifferential', 'goalDifferential']
const icehockey_nhl_offensive_stats = ['shotsTotal', 'shotsMissed', 'pointsPerGame', 'totalFaceOffs', 'faceoffsWon', 'faceoffsLost', 'faceoffPercent', 'shotsIn1stPeriod', 'shotsIn2ndPeriod', 'shotsIn3rdPeriod', 'giveaways', 'points', 'goals', 'shootingPct', 'assists']
const icehockey_nhl_defensive_stats = ['shotsAgainst', 'saves', 'savePct', 'blockedShots', 'hits', 'takeaways', 'goalsAgainst', 'powerPlayOpportunities', 'powerPlayAssists', 'powerPlayGoals', 'powerPlayPct']
const icehockey_nhl_penalty_stats = ['penaltyMinutes', 'PIMDifferential', 'penaltyKillPct', 'powerPlayGoalsAgainst', 'timesShortHanded']

const baseball_mlb_stats = [
    "seasonWinLoss",
    "homeWinLoss",
    "awayWinLoss",
    "pointDiff",
    "gamesPlayed",
    "strikeouts_pitching",
    "strikeouts_batting",
    "hits",
    "runs",
    "atBats",
    "pitches",
    "plateAppearances",
    "runsCreated",
    "runsCreatedPer27Outs",
    "pitchesPerPlateAppearance",
    "MLBRating",
    "groundBalls",
    "flyBalls",
    "battersFaced",
    "thirdInnings",
    "gamesStarted",
    "fullInnings",
    "innings",
    "groundToFlyRatio",
    "pitchesPerInning",
    "BIPA",
    "strikes",
    "putouts",
    "successfulChances",
    "totalChances",
    "fieldingPct",
    "onBasePct",
    "OPS",
    "patienceRatio",
    "opponentOnBasePct",
    "opponentOPS",
    "runnersLeftOnBase",
    "WHIP",
    "assists",
    "strikeoutsPerNineInnings",
    "batterRating",
    "totalBases",
    "avg",
    "slugAvg",
    "opponentTotalBases",
    "opponentAvg",
    "opponentSlugAvg",
    "walks",
    "RBIs",
    "doubles",
    "walksPerPlateAppearance",
    "walkToStrikeoutRatio",
    "strikeoutToWalkRatio",
    "runsProduced",
    "extraBaseHits",
    "isolatedPower",
    "earnedRuns",
    "ERA",
    "teamEarnedRuns",
    "pitchCount",
    "strikePitchRatio",
    "finishes",
    "pitchesAsStarter",
    "pitchesPerStart",
    "homeRuns",
    "outsOnField",
    "rangeFactor",
    "catcherThirdInningsPlayed",
    "runSupport",
    "runSupportAvg",
    "atBatsPerHomeRun",
    "stolenBases",
    "hitByPitch",
    "doublePlays",
    "inheritedRunners",
    "GIDPs",
    "losses",
    "wins",
    "winPct",
]

const baseball_mlb_batting_stats = ['gamesPlayed', 'strikeouts_batting', 'hits', 'runs', 'atBats', 'plateAppearances', 'runsCreated', 'pitchesPerPlateAppearance', 'MLBRating', 'groundBalls_batting', 'flyBalls_batting', 'groundToFlyRatio_batting', 'BIPA', 'onBasePct', 'OPS', 'patienceRatio', 'runnersLeftOnBase', 'batterRating', 'totalBases', 'avg', 'slugAvg', 'walks_batting', 'RBIs', 'doubles', 'walksPerPlateAppearance', 'walkToStrikeoutRatio', 'runsProduced', 'extraBaseHits', 'isolatedPower', 'homeRuns', 'atBatsPerHomeRun', 'stolenBases', 'hitByPitch', 'GIDPs', 'runsCreatedPer27Outs']
const baseball_mlb_pitching_stats = ['strikeouts_pitching', 'pitches', 'groundBalls', 'flyBalls', 'battersFaced', 'thirdInnings', 'gamesStarted', 'fullInnings', 'innings', 'groundToFlyRatio', 'pitchesPerInning', 'strikes', 'opponentOnBasePct', 'opponentOPS', 'WHIP', 'strikeoutsPerNineInnings', 'opponentTotalBases', 'opponentAvg', 'opponentSlugAvg', 'walks', 'strikeoutToWalkRatio', 'earnedRuns', 'ERA', 'teamEarnedRuns', 'pitchCount', 'strikePitchRatio', 'finishes', 'pitchesAsStarter', 'pitchesPerStart', 'homeRuns_pitching', 'runSupport', 'runSupportAvg', 'inheritedRunners', 'losses', 'wins', 'winPct']
const baseball_mlb_fielding_stats = ['putouts', 'successfulChances', 'totalChances', 'fieldingPct', 'assists', 'outsOnField', 'rangeFactor', 'catcherThirdInningsPlayed', 'doublePlays']

export const statConfigMap = {
    "baseball_mlb": {
        "default": baseball_mlb_stats,
        "categories": {
            "batting": baseball_mlb_batting_stats,
            "pitching": baseball_mlb_pitching_stats,
            "fielding": baseball_mlb_fielding_stats
        }
    },
    "americanfootball_nfl": {
        "default": americanfootball_nfl_stats,
        "categories": {
            "general": americanfootball_nfl_general_stats,
            "passing": americanfootball_nfl_passing_stats,
            "rushing": americanfootball_nfl_rushing_stats,
            "receiving": americanfootball_nfl_receiving_stats,
            "special_teams": americanfootball_nfl_special_teams_stats,
            "defensive": americanfootball_nfl_defensive_stats,
            "miscellaneous": americanfootball_nfl_miscellaneous_stats,
        }
    },
    "americanfootball_ncaaf": {
        "default": americanfootball_ncaaf_stats,
        "categories": {
            "general": americanfootball_ncaaf_general_stats,
            "passing": americanfootball_ncaaf_passing_stats,
            "rushing": americanfootball_ncaaf_rushing_stats,
            "receiving": americanfootball_ncaaf_receiving_stats,
            "special_teams": americanfootball_ncaaf_special_teams_stats,
            "defensive": americanfootball_ncaaf_defensive_stats,
            "miscellaneous": americanfootball_ncaaf_miscellaneous_stats,
        }
    },
    "basketball_nba": {
        "default": basketball_nba_stats,
        "categories": {
            "offensive": basketball_nba_offensive_stats,
            "defensive": basketball_nba_defensive_stats,
            "general": basketball_nba_general_stats
        }
    },
    "basketball_ncaab": {
        "default": basketball_ncaab_stats,
        "categories": {
            "offensive": basketball_ncaab_offensive_stats,
            "defensive": basketball_ncaab_defensive_stats,
            "general": basketball_ncaab_general_stats
        }
    },
    "basketball_wncaab": {
        "default": basketball_wncaab_stats,
        "categories": {
            "offensive": basketball_wncaab_offensive_stats,
            "defensive": basketball_wncaab_defensive_stats,
            "general": basketball_wncaab_general_stats
        }
    },
    "icehockey_nhl": {
        "default": icehockey_nhl_stats,
        "categories": {
            "offensive": icehockey_nhl_offensive_stats,
            "defensive": icehockey_nhl_defensive_stats,
            "general": icehockey_nhl_general_stats,
            "penalty": icehockey_nhl_penalty_stats
        }
    }
}

export const allStatLabels = {
    seasonWinLoss: 'Season Win-Loss',
    homeWinLoss: 'Home Win-Loss',
    awayWinLoss: 'Away Win-Loss',
    pointDiff: 'Point Differential',
    gamesPlayed: "Games Played",
    netTotalYards: "Net Total Yards",
    netYardsPerGame: "Net Yards per Game",
    totalOffensivePlays: "Total Offensive Plays",
    totalYards: "Total Yards",
    totalYardsFromScrimmage: "Total Yards from Scrimmage",
    yardsFromScrimmagePerGame: "Scrimmage Yards per Game",
    yardsPerGame: "Yards per Game",
    longRushing: "Long Rush",
    rushingAttempts: "Rushing Attempts",
    firstDowns: "First Downs",
    firstDownsPerGame: "First Downs per Game",
    passingAttempts: "Passing Attempts",
    possessionTimeSeconds: "Time of Possession (Seconds)",
    thirdDownAttempts: "3rd Down Attempts",
    rushingYards: "Rushing Yards",
    rushingYardsPerGame: "Rushing Yards per Game",
    yardsPerRushAttempt: "Yards per Rush Attempt",
    netPassingYards: "Net Passing Yards",
    netPassingYardsPerGame: "Net Passing Yards per Game",
    netYardsPerPassAttempt: "Net Yards per Pass Attempt",
    ESPNWRRating: "ESPN WR Rating",
    receptions: "Receptions",
    completionPct: "Completion Percentage",
    completions: "Completions",
    receivingYards: "Receiving Yards",
    receivingYardsAtCatch: "Yards at Catch",
    receivingYardsPerGame: "Receiving Yards per Game",
    yardsPerReception: "Yards per Reception",
    passingYards: "Passing Yards",
    passingYardsAtCatch: "Passing Yards at Catch",
    passingYardsPerGame: "Passing Yards per Game",
    yardsPerCompletion: "Yards per Completion",
    yardsPerPassAttempt: "Yards per Pass Attempt",
    ESPNRBRating: "ESPN RB Rating",
    longReception: "Long Reception",
    ESPNQBRating: "ESPN QB Rating",
    longPassing: "Long Pass",
    firstDownsPassing: "Passing First Downs",
    firstDownsRushing: "Rushing First Downs",
    kickoffs: "Kickoffs",
    totalPenalties: "Total Penalties",
    totalPenaltyYards: "Penalty Yards",
    thirdDownConvPct: "3rd Down Conversion %",
    thirdDownConvs: "3rd Down Conversions",
    yardsAllowed: "Yards Allowed",
    punts: "Punts",
    grossAvgPuntYards: "Gross Punt Average",
    puntYards: "Punt Yards",
    longPunt: "Long Punt",
    totalPoints: "Total Points",
    totalPointsPerGame: "Points per Game",
    sacks: "Sacks",
    totalKickingPoints: "Total Kicking Points",
    totalTouchdowns: "Total Touchdowns",
    totalDrives: "Total Drives",
    yardsPerReturn: "Yards per Return",
    extraPointAttempts: "Extra Point Attempts",
    kickExtraPoints: "Extra Points",
    kickExtraPointsMade: "Extra Points Made",
    extraPointPct: "Extra Point %",
    extraPointsMade: "Extra Points Made",
    totalTackles: "Total Tackles",
    soloTackles: "Solo Tackles",
    assistTackles: "Assisted Tackles",
    tacklesForLoss: "Tackles for Loss",
    kickReturns: "Kick Returns",
    passesDefended: "Passes Defended",
    kickReturnYards: "Kick Return Yards",
    longKickReturn: "Long Kick Return",
    fourthDownAttempts: "4th Down Attempts",
    kickoffReturns: "Kickoff Returns",
    interceptions: "Interceptions",
    avgKickoffReturnYards: "Avg Kickoff Return Yards",
    touchbacks: "Touchbacks",
    touchbackPct: "Touchback %",
    avgSackYards: "Avg Sack Yards",
    firstDownsPenalty: "Penalty First Downs",
    passingTouchdowns: "Passing Touchdowns",
    sackYardsLost: "Sack Yards Lost",
    receivingTouchdowns: "Receiving Touchdowns",
    passingTouchdownPct: "Passing TD %",
    sackYards: "Sack Yards",
    rushingTouchdowns: "Rushing Touchdowns",
    fieldGoalAttempts: "Field Goal Attempts",
    puntReturns: "Punt Returns",
    puntsInside20: "Punts Inside 20",
    puntsInside20Pct: "Inside 20 %",
    hurries: "QB Hurries",
    fumbles: "Fumbles",
    fieldGoalPct: "Field Goal %",
    fieldGoalsMade: "Field Goals Made",
    fieldGoals: "Field Goals",
    fourthDownConvs: "4th Down Conversions",
    fourthDownConvPct: "4th Down Conversion %",
    turnOverDifferential: "Turnover Differential",
    netPassingAttempts: "Net Passing Attempts",
    receivingTargets: "Receiving Targets",
    receivingYardsAfterCatch: "Yards After Catch",
    rushingFirstDowns: "Rushing First Downs",   // new alias not seen before
    pointsAllowed: "Points Allowed",
    stuffs: "Run Stuffs",
    puntReturnYards: "Punt Return Yards",
    avgPuntReturnYards: "Avg Punt Return Yards",
    fieldGoalAttemptYards: "Field Goal Attempt Yards",
    twoPointRecConvs: "2-Point Receiving Conversions",
    passingFirstDowns: "Passing First Downs",   // unique compared to firstDownsPassing
    fieldGoalsMadeYards: "Field Goal Made Yards",
    longFieldGoalMade: "Long Field Goal Made",
    avgKickoffYards: "Avg Kickoff Yards",
    kickoffYards: "Kickoff Yards",
    kickoffReturnYards: "Kickoff Return Yards",
    yardsPerPuntReturn: "Yards per Punt Return",
    longPuntReturn: "Long Punt Return",
    defensiveRebounds: "Defensive Rebounds",
    avgDefensiveRebounds: "Avg Defensive Rebounds",
    fouls: "Fouls",
    rebounds: "Rebounds",
    NBARating: "NBA Rating",
    avgRebounds: "Avg Rebounds",
    avgFouls: "Avg Fouls",
    assistTurnoverRatio: "Assist/Turnover Ratio",
    totalRebounds: "Total Rebounds",
    assists: "Assists",
    fieldGoals: "Field Goals",
    fieldGoalsAttempted: "Field Goals Attempted",
    fieldGoalsMade: "Field Goals Made",
    fieldGoalPct: "Field Goal %",
    points: "Points",
    turnovers: "Turnovers",
    threePointPct: "3PT %",
    threePointFieldGoalsAttempted: "3PT Attempts",
    threePointFieldGoalsMade: "3PT Made",
    pointsInPaint: "Points in the Paint",
    avgFieldGoalsMade: "Avg Field Goals Made",
    avgFieldGoalsAttempted: "Avg Field Goals Attempted",
    avgThreePointFieldGoalsMade: "Avg 3PT Made",
    avgThreePointFieldGoalsAttempted: "Avg 3PT Attempts",
    avgPoints: "Avg Points",
    avgAssists: "Avg Assists",
    avgTurnovers: "Avg Turnovers",
    estimatedPossessions: "Estimated Possessions",
    avgEstimatedPossessions: "Avg Estimated Possessions",
    pointsPerEstimatedPossessions: "Points per Estimated Possession",
    threePointFieldGoalPct: "3PT FG %",
    twoPointFieldGoalsMade: "2PT Made",
    twoPointFieldGoalsAttempted: "2PT Attempts",
    avgTwoPointFieldGoalsMade: "Avg 2PT Made",
    avgTwoPointFieldGoalsAttempted: "Avg 2PT Attempts",
    twoPointFieldGoalPct: "2PT FG %",
    shootingEfficiency: "Shooting Efficiency",
    scoringEfficiency: "Scoring Efficiency",
    freeThrowPct: "Free Throw %",
    freeThrowsAttempted: "Free Throws Attempted",
    freeThrowsMade: "Free Throws Made",
    avgFreeThrowsMade: "Avg Free Throws Made",
    avgFreeThrowsAttempted: "Avg Free Throws Attempted",
    offensiveRebounds: "Offensive Rebounds",
    avgOffensiveRebounds: "Avg Offensive Rebounds",
    offensiveReboundPct: "Offensive Rebound %",
    totalTurnovers: "Total Turnovers",
    avgTotalTurnovers: "Avg Total Turnovers",
    turnoverPoints: "Points off Turnovers",
    steals: "Steals",
    avgSteals: "Avg Steals",
    stealFoulRatio: "Steal/Foul Ratio",
    stealTurnoverRatio: "Steal/Turnover Ratio",
    fastBreakPoints: "Fast Break Points",
    blocks: "Blocks",
    avgBlocks: "Avg Blocks",
    blockFoulRatio: "Block/Foul Ratio",
    shotsAgainst: "Shots Against",
    saves: "Saves",
    savePct: "Save %",
    blockedShots: "Blocked Shots",
    hits: "Hits",
    shifts: "Shifts",
    shotsTotal: "Total Shots",
    shotsMissed: "Missed Shots",
    pointsPerGame: "Points per Game",
    totalFaceOffs: "Total Faceoffs",
    faceoffsWon: "Faceoffs Won",
    faceoffsLost: "Faceoffs Lost",
    faceoffPercent: "Faceoff %",
    shotsIn1stPeriod: "Shots in 1st Period",
    shotsIn2ndPeriod: "Shots in 2nd Period",
    shotsIn3rdPeriod: "Shots in 3rd Period",
    giveaways: "Giveaways",
    takeaways: "Takeaways",
    penalties: "Penalties",
    penaltyMinutes: "Penalty Minutes",
    timesShortHanded: "Times Short-Handed",
    powerPlayOpportunities: "Power Play Opportunities",
    shotDifferential: "Shot Differential",
    goalsAgainst: "Goals Against",
    goals: "Goals",
    shootingPct: "Shooting %",
    penaltyKillPct: "Penalty Kill %",
    goalDifferential: "Goal Differential",
    PIMDifferential: "PIM Differential",
    powerPlayAssists: "Power Play Assists",
    powerPlayGoalsAgainst: "Power Play Goals Against",
    powerPlayGoals: "Power Play Goals",
    powerPlayPct: "Power Play %",
    strikeouts_pitching: "Strikeouts (Pitching)",
    strikeouts_batting: "Strikeouts (Batting)",
    runs: "Runs",
    atBats: "At Bats",
    pitches: "Pitches",
    plateAppearances: "Plate Appearances",
    runsCreated: "Runs Created",
    runsCreatedPer27Outs: "Runs Created per 27 Outs",
    pitchesPerPlateAppearance: "Pitches per Plate Appearance",
    MLBRating: "MLB Rating",
    groundBalls: "Ground Balls",
    flyBalls: "Fly Balls",
    battersFaced: "Batters Faced",
    thirdInnings: "Third Innings",
    gamesStarted: "Games Started",
    fullInnings: "Full Innings",
    innings: "Innings",
    groundToFlyRatio: "Ground-to-Fly Ratio",
    pitchesPerInning: "Pitches per Inning",
    BIPA: "Balls in Play Against",
    strikes: "Strikes",
    putouts: "Putouts",
    successfulChances: "Successful Chances",
    totalChances: "Total Chances",
    fieldingPct: "Fielding %",
    onBasePct: "On-Base %",
    OPS: "OPS",
    patienceRatio: "Patience Ratio",
    opponentOnBasePct: "Opponent On-Base %",
    opponentOPS: "Opponent OPS",
    runnersLeftOnBase: "Runners Left on Base",
    WHIP: "WHIP",
    strikeoutsPerNineInnings: "Strikeouts per 9 Innings",
    batterRating: "Batter Rating",
    totalBases: "Total Bases",
    avg: "Batting Average",
    slugAvg: "Slugging Average",
    opponentTotalBases: "Opponent Total Bases",
    opponentAvg: "Opponent Batting Average",
    opponentSlugAvg: "Opponent Slugging Average",
    walks: "Walks",
    RBIs: "RBIs",
    doubles: "Doubles",
    walksPerPlateAppearance: "Walks per Plate Appearance",
    walkToStrikeoutRatio: "Walk-to-Strikeout Ratio",
    strikeoutToWalkRatio: "Strikeout-to-Walk Ratio",
    runsProduced: "Runs Produced",
    extraBaseHits: "Extra-Base Hits",
    isolatedPower: "Isolated Power",
    earnedRuns: "Earned Runs",
    ERA: "ERA",
    teamEarnedRuns: "Team Earned Runs",
    pitchCount: "Pitch Count",
    strikePitchRatio: "Strike/Pitch Ratio",
    finishes: "Finishes",
    pitchesAsStarter: "Pitches as Starter",
    pitchesPerStart: "Pitches per Start",
    homeRuns: "Home Runs",
    outsOnField: "Outs on Field",
    rangeFactor: "Range Factor",
    catcherThirdInningsPlayed: "Catcher Third Innings Played",
    runSupport: "Run Support",
    runSupportAvg: "Run Support Average",
    atBatsPerHomeRun: "At Bats per Home Run",
    stolenBases: "Stolen Bases",
    hitByPitch: "Hit by Pitch",
    doublePlays: "Double Plays",
    inheritedRunners: "Inherited Runners",
    GIDPs: "Ground Into Double Play",
    losses: "Losses",
    wins: "Wins",
    winPct: "Win %"
}

export const allStatNamesShort = {
  // Football - NFL & NCAAF
  seasonWinLoss: "Season W/L",
  homeWinLoss: "Home W/L",
  awayWinLoss: "Away W/L",
  pointDiff: "Point Diff",
  gamesPlayed: "Games",
  netTotalYards: "Net Yards",
  netYardsPerGame: "Net Yds/Game",
  totalOffensivePlays: "Off Plays",
  totalYards: "Total Yards",
  totalYardsFromScrimmage: "Scrimmage Yards",
  yardsFromScrimmagePerGame: "Scrim Yds/Game",
  yardsPerGame: "Yds/Game",
  longRushing: "Long Rush",
  rushingAttempts: "Rush Att",
  firstDowns: "1st Downs",
  firstDownsPerGame: "1st Downs/Game",
  passingAttempts: "Pass Att",
  possessionTimeSeconds: "Poss Time",
  thirdDownAttempts: "3rd Down Att",
  rushingYards: "Rush Yards",
  rushingYardsPerGame: "Rush Yds/Game",
  yardsPerRushAttempt: "Yds/Rush",
  netPassingYards: "Net Pass Yards",
  netPassingYardsPerGame: "Net Pass Yds/Game",
  netYardsPerPassAttempt: "Yds/Pass Att",
  receivingTargets: "Rec Targets",
  ESPNRBRating: "RB Rating",
  longReception: "Long Rec",
  receptions: "Receptions",
  completionPct: "Comp %",
  completions: "Completions",
  receivingYards: "Rec Yards",
  receivingYardsAtCatch: "Yds/Catch",
  receivingYardsPerGame: "Rec Yds/Game",
  yardsPerReception: "Yds/Rec",
  passingYards: "Pass Yards",
  passingYardsAtCatch: "Pass Yds/Catch",
  passingYardsPerGame: "Pass Yds/Game",
  yardsPerCompletion: "Yds/Comp",
  yardsPerPassAttempt: "Yds/Pass",
  ESPNWRRating: "WR Rating",
  ESPNQBRating: "QB Rating",
  longPassing: "Long Pass",
  firstDownsPassing: "1st Down Pass",
  firstDownsRushing: "1st Down Rush",
  kickoffs: "Kickoffs",
  totalPenalties: "Penalties",
  totalPenaltyYards: "Penalty Yards",
  thirdDownConvPct: "3rd Down %",
  thirdDownConvs: "3rd Down Conv",
  yardsAllowed: "Yards Allowed",
  punts: "Punts",
  grossAvgPuntYards: "Punt Avg",
  puntYards: "Punt Yards",
  longPunt: "Long Punt",
  totalPoints: "Points",
  totalPointsPerGame: "Pts/Game",
  sacks: "Sacks",
  totalKickingPoints: "Kick Pts",
  totalTouchdowns: "TDs",
  totalDrives: "Drives",
  yardsPerReturn: "Yds/Return",
  extraPointAttempts: "XP Att",
  kickExtraPoints: "Kick XP",
  kickExtraPointsMade: "Kick XP Made",
  extraPointPct: "XP %",
  extraPointsMade: "XP Made",
  totalTackles: "Tackles",
  soloTackles: "Solo Tackles",
  assistTackles: "Assist Tack",
  tacklesForLoss: "TFL",
  kickReturns: "Kick Returns",
  passesDefended: "PD",
  kickReturnYards: "Kick Ret Yds",
  longKickReturn: "Long Kick Ret",
  fourthDownAttempts: "4th Down Att",
  kickoffReturns: "KO Returns",
  interceptions: "INTs",
  defensive_interceptions: "Def INTs",
  avgKickoffReturnYards: "KO Ret Avg",
  touchbacks: "Touchbacks",
  touchbackPct: "TB %",
  touchbacks_punting: "TB Punting",
  touchbackPct_punting: "TB % Punt",
  avgSackYards: "Avg Sack Yds",
  firstDownsPenalty: "1st Down Pen",
  passingTouchdowns: "Pass TDs",
  sackYardsLost: "Sack Yds Lost",
  receivingTouchdowns: "Rec TDs",
  passingTouchdownPct: "Pass TD %",
  sackYards: "Sack Yards",
  rushingTouchdowns: "Rush TDs",
  fieldGoalAttempts: "FG Att",
  puntReturns: "Punt Returns",
  puntsInside20: "Punts <20",
  puntsInside20Pct: "Punts <20 %",
  hurries: "Hurries",
  fumbles: "Fumbles",
  fieldGoalPct: "FG %",
  fieldGoalsMade: "FG Made",
  fieldGoals: "FG",
  fourthDownConvs: "4th Down Conv",
  fourthDownConvPct: "4th Down %",
  turnOverDifferential: "TO Diff",

  // NBA + NCAA + WNBA
  defensiveRebounds: "Def Reb",
  avgDefensiveRebounds: "Avg Def Reb",
  fouls: "Fouls",
  rebounds: "Rebounds",
  NBARating: "NBA Rating",
  avgRebounds: "Avg Reb",
  avgFouls: "Avg Fouls",
  assistTurnoverRatio: "AST/TO Ratio",
  totalRebounds: "Total Reb",
  fieldGoals: "FG",
  fieldGoalsAttempted: "FG Att",
  fieldGoalsMade: "FG Made",
  fieldGoalPct: "FG %",
  points: "Points",
  turnovers: "TO",
  threePointPct: "3P %",
  threePointFieldGoalsAttempted: "3P Att",
  threePointFieldGoalsMade: "3P Made",
  pointsInPaint: "Pts in Paint",
  avgFieldGoalsMade: "Avg FG Made",
  avgFieldGoalsAttempted: "Avg FG Att",
  avgThreePointFieldGoalsMade: "Avg 3P Made",
  avgThreePointFieldGoalsAttempted: "Avg 3P Att",
  avgPoints: "Avg Points",
  avgAssists: "Avg AST",
  avgTurnovers: "Avg TO",
  estimatedPossessions: "Est Poss",
  avgEstimatedPossessions: "Avg Est Poss",
  pointsPerEstimatedPossessions: "Pts/Est Poss",
  threePointFieldGoalPct: "3P %",
  twoPointFieldGoalsMade: "2P Made",
  twoPointFieldGoalsAttempted: "2P Att",
  avgTwoPointFieldGoalsMade: "Avg 2P Made",
  avgTwoPointFieldGoalsAttempted: "Avg 2P Att",
  twoPointFieldGoalPct: "2P %",
  shootingEfficiency: "Shooting Eff",
  scoringEfficiency: "Scoring Eff",
  freeThrowPct: "FT %",
  freeThrowsAttempted: "FT Att",
  freeThrowsMade: "FT Made",
  avgFreeThrowsMade: "Avg FT Made",
  avgFreeThrowsAttempted: "Avg FT Att",
  offensiveRebounds: "Off Reb",
  avgOffensiveRebounds: "Avg Off Reb",
  offensiveReboundPct: "Off Reb %",
  totalTurnovers: "Total TO",
  avgTotalTurnovers: "Avg Total TO",
  turnoverPoints: "TO Pts",
  steals: "Steals",
  avgSteals: "Avg Steals",
  stealFoulRatio: "Steal/Foul",
  stealTurnoverRatio: "Steal/TO",
  fastBreakPoints: "FB Pts",
  blocks: "Blocks",
  avgBlocks: "Avg Blocks",
  blockFoulRatio: "Block/Foul",

  // NHL
  shotsAgainst: "Shots Against",
  saves: "Saves",
  savePct: "Save %",
  blockedShots: "Blocked Shots",
  hits: "Hits",
  shifts: "Shifts",
  shotsTotal: "Shots Total",
  shotsMissed: "Shots Missed",
  pointsPerGame: "Pts/Game",
  totalFaceOffs: "Total Faceoffs",
  faceoffsWon: "Faceoffs Won",
  faceoffsLost: "Faceoffs Lost",
  faceoffPercent: "Faceoff %",
  shotsIn1stPeriod: "Shots 1st",
  shotsIn2ndPeriod: "Shots 2nd",
  shotsIn3rdPeriod: "Shots 3rd",
  giveaways: "Giveaways",
  takeaways: "Takeaways",
  penalties: "Penalties",
  penaltyMinutes: "PIM",
  timesShortHanded: "SH Times",
  powerPlayOpportunities: "PP Opp",
  shotDifferential: "Shot Diff",
  goalsAgainst: "GA",
  goals: "Goals",
  shootingPct: "Shooting %",
  penaltyKillPct: "PK %",
  goalDifferential: "Goal Diff",
  PIMDifferential: "PIM Diff",
  powerPlayAssists: "PP Assists",
  powerPlayGoalsAgainst: "PP GA",
  powerPlayGoals: "PP Goals",
  powerPlayPct: "PP %",
  
  // MLB
  strikeouts_pitching: "K Pitch",
  strikeouts_batting: "K Bat",
  runs: "Runs",
  atBats: "AB",
  pitches: "Pitches",
  plateAppearances: "PA",
  runsCreated: "RC",
  runsCreatedPer27Outs: "RC/27",
  pitchesPerPlateAppearance: "P/PA",
  MLBRating: "MLB Rating",
  groundBalls: "GB",
  flyBalls: "FB",
  battersFaced: "BF",
  thirdInnings: "3rd Inn",
  gamesStarted: "GS",
  fullInnings: "Full Inn",
  innings: "Innings",
  groundToFlyRatio: "G/F Ratio",
  pitchesPerInning: "P/Inning",
  BIPA: "BIPA",
  strikes: "Strikes",
  putouts: "Putouts",
  successfulChances: "Suc Chances",
  totalChances: "Tot Chances",
  fieldingPct: "Fld %",
  onBasePct: "OBP",
  OPS: "OPS",
  patienceRatio: "Patience",
  opponentOnBasePct: "Opp OBP",
  opponentOPS: "Opp OPS",
  runnersLeftOnBase: "RLOB",
  WHIP: "WHIP",
  strikeoutsPerNineInnings: "K/9",
  batterRating: "Batter Rating",
  totalBases: "TB",
  avg: "AVG",
  slugAvg: "SLG",
  opponentTotalBases: "Opp TB",
  opponentAvg: "Opp AVG",
  opponentSlugAvg: "Opp SLG",
  walks: "BB",
  RBIs: "RBI",
  doubles: "2B",
  walksPerPlateAppearance: "BB/PA",
  walkToStrikeoutRatio: "BB/K",
  strikeoutToWalkRatio: "K/BB",
  runsProduced: "RP",
  extraBaseHits: "XBH",
  isolatedPower: "ISO",
  earnedRuns: "ER",
  ERA: "ERA",
  teamEarnedRuns: "Team ER",
  pitchCount: "Pitch Ct",
  strikePitchRatio: "S/P",
  finishes: "Finishes",
  pitchesAsStarter: "P as Starter",
  pitchesPerStart: "P/Start",
  homeRuns: "HR",
  outsOnField: "Outs",
  rangeFactor: "Range Factor",
  catcherThirdInningsPlayed: "C 3rd Inn",
  runSupport: "Run Support",
  runSupportAvg: "Run Sup Avg",
  atBatsPerHomeRun: "AB/HR",
  stolenBases: "SB",
  hitByPitch: "HBP",
  doublePlays: "DP",
  inheritedRunners: "IR",
  GIDPs: "GIDP",
  losses: "Losses",
  wins: "Wins",
  winPct: "Win %"
};
